<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Experience;
use App\Models\Job;
use App\Models\JobCompetence;
use App\Models\Knowledge;

class CORPPuestosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $job = Job::firstOrCreate(["name" => "Presidente de Consejo"]);
        $job = Job::firstOrCreate(["name" => "Presidente de Consejo"]);
        $job = Job::firstOrCreate(["name" => "Presidente de Consejo"]);
        $job = Job::firstOrCreate(["name" => "Director General"]);
        $job = Job::firstOrCreate(["name" => "Director General"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Financieros", "notas" => "Específicos:\n- Presupuestos\n- Proyecciones Financieras\n- Análisis Financieros\n- Elaboración y Análisis de Estados Financieros\n\nBases:\n- Matemáticas Financieras\n- Evaluación de Proyectos Financieros\n- Entendimiento de Estados Financieros\n- Inversiones\n- Presupuestos"]);
        $job = Job::firstOrCreate(["name" => "Director General"]);
        Experience::create(["job_id" => $job->id, "name" => "Manejo de los accionistas y del Consejo de Administración.", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Gobierno Corporativo", "notas" => "Cómo debe de funcionar un gobierno Corporativo"]);
        Experience::create(["job_id" => $job->id, "name" => "Lograr que se viva la cultura del Grupo.", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Estrategias de Negociación ", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Negociaciones continuas internas y externas.", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Marco Legal Laboral (bases)", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Participación relevante en diferentes tipos de proyectos.", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Liderar con éxito equipos multidisciplinarios de alto desempeño.", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Director de Estructuración de Proyectos"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión del Riesgo", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Director de Estructuración de Proyectos"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Financieros ", "notas" => "Matemáticas Financieras\nConstrucción y Análisis de Modelos Financieros \nEvaluación de Proyectos Financieros\nEntendimiento de Estados Financieros\nInversiones (Proyectos de Inversión)\nPresupuestos\nDerivados"]);
        $job = Job::firstOrCreate(["name" => "Director de Estructuración de Proyectos"]);
        Experience::create(["job_id" => $job->id, "name" => "Haberse involucrado en negociaciones  exitosas con Gobierno Federal sobre  contratos de asociaciones público y privada.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de la Información", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Finanzas Corporativas: Mercados de Deuda y Capital", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Haber participado en el cierre de financiamiento de proyectos de infraestructura.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de Recursos", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Evaluación de Proyectos de Inversión", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Coordinar a un equipo multidisciplinario, para la ejecución y cierre de proyectos en tiempo y forma.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Creatividad e Innovación", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Regulación Asociaciones Público Privadas ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Asesoría y Acompañamiento", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas Contables (Bases)", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas Fiscales (Bases)", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Administración de Proyectos", "notas" => "1) Definición y presentación del proyecto \n2) Planificación \n3) Establecer objetivos\n\n4) Supervisión de tareas\n5) Implementación de soluciones o cambios"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Macroeconomía (contexto económico, político y social, nacional e internacional)", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Inglés", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Marco Legal Laboral (bases)", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Director de Administración y Finanzas"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión del Riesgo", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Director de Administración y Finanzas"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Financieros", "notas" => "Matemáticas Financieras\nEvaluación de Proyectos Financieros\nEntendimiento de Estados Financieros\nInversiones\nPresupuestos"]);
        $job = Job::firstOrCreate(["name" => "Director de Administración y Finanzas"]);
        Experience::create(["job_id" => $job->id, "name" => "Participación activa a reuniones de Consejo de Administración.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de la Información", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Bancarios", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Vivir y manejar periodos de crisis: de bajo flujo de caja, estrés financiero y controversias con autoridades.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de Recursos", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Seguros", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Tener éxito en negociaciones estratégicas de alto impacto (créditos, derivados, etc.)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Sentido de Urgencia", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Mercado de Derivados ", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Tener comunicación y benchmarking con puestos similares en el mercado;
ver las tendencias (exposure).", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Dominio y Cumplimiento Normativo", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Evaluación de Proyectos de Inversión", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Asesoría y Acompañamiento", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas Fiscales", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas Contables", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Capital Humano", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Leyes y Normativas Laborales", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Obligaciones Patronales del Seguro Social, INFONAVIT, etc.", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Conocimientos Generales TI", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Administración de Proyectos", "notas" => "Definición y presentación del proyecto \nPlanificación \nEstablecer objetivos\nSupervisión de tareas\nImplementación de soluciones o cambios"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Inglés", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Director de Desarrollo y Bienestar Humano"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de Recursos", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Director de Desarrollo y Bienestar Humano"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Leyes y Normativas Laborales", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Director de Desarrollo y Bienestar Humano"]);
        Experience::create(["job_id" => $job->id, "name" => "Lograr la aprobación de prácticas positivas de alto impacto para los Grupos (Días Adicionales, Días Especiales, Homeoffice...) ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión del Riesgo", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas en Bienestar (NOM035-NOM030)", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Traer a un conferencista con precios preferenciales y que otras empresas participen para traerlo.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Sensibilidad ante Situaciones", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Obligaciones Patronales del Seguro Social", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Orientación al Cliente/Servicio", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Cultura Organizacional", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Atención al Detalle", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Desarrollo Organizacional", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Creatividad e Innovación", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Prácticas de Bienestar/Psicología Positiva", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Planes de Compensación", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Administración de Proyectos", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Marco Legal Laboral (bases)", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Director Corporativo de Construcción"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de Recursos", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Director Corporativo de Construcción"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Financieros", "notas" => "Matemáticas Financieras\n- Evaluación de Proyectos Financieros\n- Entendimiento de Estados Financieros\n- Inversiones\n- Presupuestos"]);
        $job = Job::firstOrCreate(["name" => "Director Corporativo de Construcción"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión del Riesgo", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas y Sistemas de Gestión de Calidad", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Sentido de Urgencia", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Desarrollo de Infraestructura", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Edificación de Obras Civiles", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativa SCT", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Administración de Proyectos", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Marco Legal Laboral (bases)", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Gerente Jurídico"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Acatamiento de Valores", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Gerente Jurídico"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Gobierno Corporativo", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Gerente Jurídico"]);
        Experience::create(["job_id" => $job->id, "name" => "Participar activamente en Asambleas de Accionistas y Reuniones de Consejo de Administración.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Dominio y Cumplimiento Normativo", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas: Mercantil y Civil (compliance)", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Encontrar la solución a problemas críticos que ponen en riesgo la consecución de los proyectos de la empresa.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de la Información", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Marco Legal Laboral (bases)", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Cerrar negociaciones y contrataciones de alto nivel, tanto a nivel privado (clientes, inversionistas, etc.), como a nivel  sector público.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Detección, Prevención y Mitigación de Riesgos", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Propiedad Intelectual e Industrial", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Asesoría y Acompañamiento", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Protección de Datos", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Toma de Decisiones Asertiva", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Administración de Proyectos", "notas" => "Definición y presentación del proyecto \nPlanificación \nEstablecer objetivos\nSupervisión de tareas\nImplementación de soluciones o cambios"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Comunicación Escrita", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Dirección Estratégica Corporativa"]);
        $job = Job::firstOrCreate(["name" => "Dirección Estratégica Corporativa"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Relaciones Institucionales", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Dirección Estratégica Corporativa"]);
        Experience::create(["job_id" => $job->id, "name" => "Manejo de los accionistas y del Consejo de Administración.", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Marco Jurídico de Negocios (corporativo, agrario, energía, bienes raíces, de la empresa..)", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Negociaciones continuas con autoridades y particulares.", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Administración y Evaluación de Proyectos", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Lograr que se viva la cultura del Grupo.", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Estrategias de Negociación ", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Liderar con éxito equipos multidisciplinarios de alto desempeño.", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Marco Legal Laboral (bases)", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Asistente de Dirección"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Orientación al Servicio", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Asistente de Dirección"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Paquetería Office", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Asistente de Dirección"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Plataformas GB Travel", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Recepción y Asistente de Dirección"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Colaboración", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Recepción y Asistente de Dirección"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Paquetería Office", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Recepción y Asistente de Dirección"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Confiabilidad", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Manejo de Conmutador ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Comunicación oral y escrita", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Facturación ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Orientación al Servicio", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Orientación a las Tecnologías de Información", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Planeación y Organización ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Especialista en Comunicación Institucional"]);
        $job = Job::firstOrCreate(["name" => "Especialista en Comunicación Institucional"]);
        $job = Job::firstOrCreate(["name" => "Especialista en Comunicación Institucional"]);
        $job = Job::firstOrCreate(["name" => "Director de Relaciones Institucionales"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Investigación", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Director de Relaciones Institucionales"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Conocimientos Técnicos en Infraestructura", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Director de Relaciones Institucionales"]);
        Experience::create(["job_id" => $job->id, "name" => "Negociaciones continuas con autoridades y particulares.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de la Información", "notas" => "Administrar la información y bajarla"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Diseño y aplicación de Estrategia Comerciales/Negociación", "notas" => "Saber vender una idea/proyecto"]);
        Experience::create(["job_id" => $job->id, "name" => "Ser parte de foros, consejos...(actualización continua)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Estrategia Comercial/Negociación", "notas" => "Saber vender una idea/proyecto"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Marco Jurídico de Negocios (corporativo, agrario, energía, bienes raíces, de la empresa..)", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Estar en campo en la operación.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Orientación al Cliente", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Relaciones Institucionales", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Organizar con éxito equipos multidisciplinarios de alto desempeño.", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Administración de Proyectos", "notas" => "Definición y presentación del proyecto \nPlanificación \nEstablecer objetivos\nSupervisión de tareas\n Implementación de soluciones o cambios"]);
        $job = Job::firstOrCreate(["name" => "Auxiliar Administrativo"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Atención al Detalle", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Auxiliar Administrativo"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Paquetería Office ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Auxiliar Administrativo"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad Numérica", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "ERPs de Contabilidad (Neodata, Nav y Fortia)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Planificación y Organización", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Facturación", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad Analítica ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Portales bancarios ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Actitud de Servicio", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Optimización del Tiempo", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Trabajo en Equipo ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Gerente de Compliance y Nuevos Proyectos"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Visión Financiera del Negocio", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Gerente de Compliance y Nuevos Proyectos"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Sistemas Administrativos Contables (ERP)", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Gerente de Compliance y Nuevos Proyectos"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión del Riesgo", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas Fiscales", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de la Información", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Elaboración e Interpretación de Estados Financieros ", "notas" => "Estados financieros/contables básicos:\n- Estado de Resultados\n- Balance General\n- Flujo de Efectivo\n- Estado de Cambios de Capital"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de Recursos", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Leyes y Normativas Laborales", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Sentido de Oportunidad", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Obligaciones Patronales del Seguro Social", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Sentido de Urgencia", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Marco Legal Laboral (bases)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Dominio y Cumplimiento Normativo", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Excel Intermedio", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Toma de Decisiones Asertiva", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Especialista Financiero de Proyectos"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Visión Financiera y del Negocio", "notas" => "Perspicacia Financiera"]);
        $job = Job::firstOrCreate(["name" => "Especialista Financiero de Proyectos"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Financieros", "notas" => "\nBases:\n- Matemáticas Financieras \n- Elaboración y Entendimiento de Estados Financieros\n- Inversiones\n- Presupuestos\n- Seguros de Riesgo\n- Mercado de Derivados"]);
        $job = Job::firstOrCreate(["name" => "Especialista Financiero de Proyectos"]);
        Experience::create(["job_id" => $job->id, "name" => "Desarrollar modelos financieros materializados/ejecutables para los proyectos del Grupo.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Pensamiento Crítico", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Evaluación de Proyectos Financieros /Construcción y Análisis de Modelos Financieros ", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Lograr un otorgamiento de crédito por parte de alguna institución financiera (Banobras...)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de la Información", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Administración de Proyectos", "notas" => "Definición y presentación del proyecto \nPlanificación \nEstablecer objetivos\nSupervisión de tareas\nImplementación de soluciones o cambios"]);
        Experience::create(["job_id" => $job->id, "name" => "Elaborar y presentar los proyectos y modelos financieros para dirección y sus avances.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Análisis", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Excel Avanzado", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Respuesta y Resolución", "notas" => "Cumplir con los tiempos de entrega (resolver problemas para que salga todo adelante)\nFlexibilidad y Adaptación al Cambio\nDisponibilidad de tiempo\nAutosupervisión"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Marco Legal Laboral (bases)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Colaboración con áreas estratégicas/Trabajo en Equipo", "notas" => "Mantener alianzas estratégicas para el logro de objetivos: TI, Contabilidad, Administración, etc.\n\n(tanto interna como externa)"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Construcción de Relaciones", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Analista de Proyectos"]);
        $job = Job::firstOrCreate(["name" => "Analista de Proyectos"]);
        $job = Job::firstOrCreate(["name" => "Analista de Proyectos"]);
        $job = Job::firstOrCreate(["name" => "Analista Financiero"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Atención al Detalle", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Analista Financiero"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Dynamics NAV ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Analista Financiero"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de análisis ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Think- cell", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad numérica ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normas de Información Financiera", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Precisión", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Excel ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Perspsicacia Financiera", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normas Internacionales de Información Financiera ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Visión Estratégica", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Análisis Financiero"]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Análisis Financiero"]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Análisis Financiero"]);
        $job = Job::firstOrCreate(["name" => "Especialista Financiero"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Visión Financiera y del Negocio", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Especialista Financiero"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Financieros", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Especialista Financiero"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Análisis", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Evaluación de Proyectos Financieros /Construcción y Análisis de Modelos Financieros ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Respuesta y Resolución", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Administración de Proyectos", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Colaboración con áreas estratégicas/Trabajo en Equipo", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Excel Avanzado", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Construcción de Relaciones", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Marco Legal Laboral (bases)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Pensamiento Crítico", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de la Información", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Planeación Financiera y Estratégica"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Visión Financiera y del Negocio", "notas" => "Perspicacia Financiera"]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Planeación Financiera y Estratégica"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Macroeconomía (contexto económico, político y social, nacional e internacional", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Planeación Financiera y Estratégica"]);
        Experience::create(["job_id" => $job->id, "name" => "Consolidar exitosamente los presupuestos anuales con todas las variantes operativas.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de la Información", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Financieros", "notas" => " Matemáticas Financieras\n- Evaluación de Proyectos Financieros\n- Inversiones\n- Presupuestos"]);
        Experience::create(["job_id" => $job->id, "name" => "Lograr un otorgamiento de crédito por parte de alguna institución financiera", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Respuesta y Resolución", "notas" => "Ej. Te piden sacar un crédito, tienes que moverte…"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas Contables (intermedio)", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Preparar la presentación del Consejo (temas operativos, financieros y avance de proyectos).", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Análisis", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas Fiscales (intermedio)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Pensamiento Crítico", "notas" => "Considerar todas las variables."]);
        Knowledge::create(["job_id" => $job->id, "name" => "Análisis y Elaboración de Estados Financieros", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Asesoría y Acompañamiento", "notas" => "Estar con ellos, buscando que se corrijan esos errores, previo a que se presenten a Dirección"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Excel Avanzado", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Colaboración con áreas estratégicas/Trabajo en Equipo", "notas" => "Mantener alianzas estratégicas para el logro de objetivos con las Uns, Bancos, etc.\n\n(tanto interna como externa)"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Marco Legal Laboral (bases)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Dominio y Cumplimiento Normativo", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Analista Sr. Financiero"]);
        $job = Job::firstOrCreate(["name" => "Analista Sr. Financiero"]);
        $job = Job::firstOrCreate(["name" => "Analista Sr. Financiero"]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Nóminas"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Orientación al Cliente/Servicio ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Nóminas"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Elaboración, Manejo y Control de Presupuestos", "notas" => " Nómina\n- del área de CH"]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Nóminas"]);
        Experience::create(["job_id" => $job->id, "name" => "Analizar y realizar reportes de los sueldos y salarios de la organización.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Orientación la Calidad", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Softwares de Nómina ", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Vivir un cambio de reforma y darle cumplimiento en tiempo y forma.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de Recursos", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Leyes y Normativas Laborales", "notas" => "LEY FEDERAL DEL TRABAJO\n- LEY DEL SEGURO SOCIAL (Obligaciones Patronales y Empleados)\n- LEY ISR- NORMATIVAS FISCALES\n\n- Cumplimiento de requisitos ante dependencias: STPS, IMSS, INFONAVIT, FONACOT, SAT (timbrado de nómina)"]);
        Experience::create(["job_id" => $job->id, "name" => "Gestionar efectivamente el pago de nómina de un alto número de colaboradores.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Habilidad Numérica", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Sistema Único de Autodeterminación (SUA) ", "notas" => "IMSS: se usa para pagar las aportaciones/cuotas del IMSS.L142"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Atención al Detalle", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "IMSS desde su Empresa (IDSE)", "notas" => "Aquí se registrar las altas y bajas de los colaboradores."]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Integridad", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Calcular Sueldos y Salarios", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Dominio y Cumplimiento Normativo", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Excel (Intermedio)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Colaboración con áreas estratégicas/Trabajo en Equipo", "notas" => "Mantener alianzas estratégicas para el logro de objetivos: TI, Contabilidad, Administración, etc."]);
        $job = Job::firstOrCreate(["name" => "Analista Sr. de Nóminas"]);
        $job = Job::firstOrCreate(["name" => "Analista Sr. de Nóminas"]);
        $job = Job::firstOrCreate(["name" => "Analista Sr. de Nóminas"]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Capital Humano"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Pensamiento Crítico", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Capital Humano"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Elaboración, Manejo y Control de Presupuestos", "notas" => " Nómina\n- del área de CH"]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Capital Humano"]);
        Experience::create(["job_id" => $job->id, "name" => "Identificar y gestionar los riesgos laborales para evitar conflictos y/o demandas. ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Mejoramiento Continuo / Orientación a la Calidad", "notas" => "Mejora de procesos e indicadores para brindar un mejor servicio"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Software de Administración de Personal", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Haber gestionado de principio a fin una baja conflictiva. ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Orientación al Cliente/Servicio ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Leyes y Normativas Laborales", "notas" => "LEY FEDERAL DEL TRABAJO\n- LEY DEL SEGURO SOCIAL (Obligaciones Patronales y Empleados)\n- LEY ISR- NORMATIVAS FISCALES (noción básica)\n\n- Cumplimiento de requisitos ante dependencias: STPS, IMSS, INFONAVIT, FONACOT (nociones básicas)"]);
        Experience::create(["job_id" => $job->id, "name" => "Proponer ajustes de compensación, con base en análisis de remuneración en el mercado, el histórico del colaborador, tabuladores y equidad interna.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Negociación, Gestión y Solución de Conflictos", "notas" => "Negociación con proveedores y clientes"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas en Bienestar  ", "notas" => "Normativas de las STPS: NOM035-NOM030- NOM019"]);
        Experience::create(["job_id" => $job->id, "name" => "Elaborar el presupuesto de nómina.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Disponibilidad", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Competitividad Salarial en la industria y el mercado", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Proponer y diseñar procesos, prácticas y políticas positivas con base a la cultura (inducción...)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Dominio y Cumplimiento Normativo", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Planes de Compensación", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Diseñar, Implementar y Reportar Indicadores Claves", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Colaboración /Trabajo en Equipo", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Desarrollo Estratégico de Capital Humano", "notas" => "Subsistemas de Capital Humano: reclutamiento, administración de personal, desarrollo y capacitación, cultura...."]);
        Knowledge::create(["job_id" => $job->id, "name" => "Excel (Intermedio)", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Analista Jr. de Atracción de Talento"]);
        $job = Job::firstOrCreate(["name" => "Analista Jr. de Atracción de Talento"]);
        $job = Job::firstOrCreate(["name" => "Analista Jr. de Atracción de Talento"]);
        $job = Job::firstOrCreate(["name" => "Analista Jr. de Capital Humano"]);
        $job = Job::firstOrCreate(["name" => "Analista Jr. de Capital Humano"]);
        $job = Job::firstOrCreate(["name" => "Analista Jr. de Capital Humano"]);
        $job = Job::firstOrCreate(["name" => "Auxiliar de Reclutamiento"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Comunicación Efectiva ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Auxiliar de Reclutamiento"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Paqutería Office ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Auxiliar de Reclutamiento"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Negociación", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Fortia", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Actitud de Servicio", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Plataformas y medios de reclutamiento", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Enfoque a Resultados ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Leyes y normativas relacionadas a la gestión de personal", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Toma de Decisiones", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Técnicas de la entrevista", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de Talento ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Gestión por competencias", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Auxiliar de Capital Humano"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Comunicación Efectiva ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Auxiliar de Capital Humano"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Paquetería Office ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Auxiliar de Capital Humano"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Negociación", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Fortia", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Actitud de Servicio", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Plataformas y medios de reclutamiento", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Enfoque a Resultados ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Leyes y normativas relacionadas a la gestión de personal", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Toma de Decisiones", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Técnicas de la entrevista", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de Talento ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Gestión por competencias", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Analista Jr. de Capital Humano"]);
        $job = Job::firstOrCreate(["name" => "Analista Jr. de Capital Humano"]);
        $job = Job::firstOrCreate(["name" => "Analista Jr. de Capital Humano"]);
        $job = Job::firstOrCreate(["name" => "Gerente Administrativo"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Visión Financiera y del Negocio", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Gerente Administrativo"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Sistemas Administrativos Contables (ERP)", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Gerente Administrativo"]);
        Experience::create(["job_id" => $job->id, "name" => "Rendición de cuentas a Consejo de Administración.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Acompañamiento y Seguimiento de Proyectos Estratégicos", "notas" => "Con todas las UDNs\nEj. Presupuestos, auditorias, reformas, nuevos sistemas, etc"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas Contables", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Hacer la planeación y administración de flujos de recursos y su aplicación a los negocios.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de la Información", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas Fiscales", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Vivir y manejar periodos de crisis: de bajo flujo de caja, estrés financiero y controversias con autoridades.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de Recursos", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Elaboración, Interpretación y Consolidación de Estados Financieros ", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Proponer estrategias financieras y fiscales de los negocios.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Sentido de Urgencia", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Elaboración, Manejo y Control de Presupuestos", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Dominio y Cumplimiento Normativo", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Administración de Nóminas (IMSS, INFONAVIT, FONACOT...)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Anticipación de Problemas", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Manejo de Bancos, Créditos Bancarios.. ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Asuntos Legales Corporativos", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Control Interno", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Administración de Proyectos", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Marco Legal Laboral (bases)", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Excel Intermedio", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Contraloría"]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Contraloría"]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Contraloría"]);
        $job = Job::firstOrCreate(["name" => "Especialista Fiscal"]);
        $job = Job::firstOrCreate(["name" => "Especialista Fiscal"]);
        $job = Job::firstOrCreate(["name" => "Especialista Fiscal"]);
        $job = Job::firstOrCreate(["name" => "Contador General"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Colaboración con áreas estratégicas/Trabajo en Equipo", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Contador General"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Sistemas Administrativos Contables (ERP)", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Contador General"]);
        Experience::create(["job_id" => $job->id, "name" => "Dar solución al 100% de las observaciones de auditorías internas y externas. ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Habilidad Numérica", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Control y Gestión de Presupuestos", "notas" => "Supervisar que se cumpla en tiempo y forma y generar ahorros."]);
        Experience::create(["job_id" => $job->id, "name" => "Haber presentado reportes de información a la gerencia.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Análisis", "notas" => "No cegarse por la operación, Ojo auditor\nPara obtener información mas confiable"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas Fiscales", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Haber lidereado la migración de un sistema ERP a otro.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de la Información", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas Contables", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Cumplimiento y Dominio Normativo", "notas" => "Normativas internas y externas"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Elaboración e Interpretación de Informes Financieros ", "notas" => "Estados financieros/contables básicos:\n- Estado de Resultados\n- Balance General\n- Flujo de Efectivo\n- Estado de Cambios de Capital"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Optimización del tiempo", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Cuentas por Cobrar y Cuentas por Pagar", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Atención a Auditorias", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Tesorería", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Marco Legal Laboral (bases)", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Excel Intermedio", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Contador Sr."]);
        $job = Job::firstOrCreate(["name" => "Contador Sr."]);
        $job = Job::firstOrCreate(["name" => "Contador Sr."]);
        $job = Job::firstOrCreate(["name" => "Contador Jr."]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Atención al detalle ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Contador Jr."]);
        Knowledge::create(["job_id" => $job->id, "name" => "Paquetería Office ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Contador Jr."]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Autodisciplina ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "ERPs de contabilidad (Neodata,Nav y Fortia)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad numérica ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Leyes y Normativas Fiscales", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Cumplimiento de normas ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Portales bancarios ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Optimización del tiempo ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Portal de Secretaría de Administración Tributaria  ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Tolerancia a la presión ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Auxiliar Administrativo"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Atención al Detalle", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Auxiliar Administrativo"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Paquetería Office ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Auxiliar Administrativo"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad Numérica", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "ERPs de Contabilidad (Neodata, Nav y Fortia)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Planificación y Organización", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Facturación", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad Analítica ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Portales bancarios ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Actitud de Servicio", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Optimización del Tiempo", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Trabajo en Equipo ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Mantenimiento"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Respuesta y Resolución", "notas" => "Disponibilidad\nDar respuesta en tiempo y forma.\nNo solo a la empresa, sino tambien ante el cliente y las diversidad dependencias;
y/o ante cualquier contingencia.\nEj. SCT"]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Mantenimiento"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Manejo y Control de Presupuestos", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Mantenimiento"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Mejoramiento Continuo / Orientación a la Calidad", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Administración y Control de Proyectos", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Dominio y Cumplimiento Normativo", "notas" => "Normativa de SCT \nNorma Oficial Mexicana \nISO "]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normatividad en Construcción de Carreteras (Normativa SCT)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de Recursos", "notas" => "Optimización de recursos para obtener ahorros "]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas de Vialidad", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Mantenimiento de Vías Terrestres", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Concreto, Pavimentos, Estructuras, Estabilización de Taludes y Cortes", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas y Sistemas de Gestión de Calidad ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Softwares de Diseño", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Marco Legal Laboral (bases)", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Chofer"]);
        $job = Job::firstOrCreate(["name" => "Chofer"]);
        $job = Job::firstOrCreate(["name" => "Chofer"]);
        $job = Job::firstOrCreate(["name" => "Gerente de Contabilidad"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión del Riesgo", "notas" => "Medir el impacto "]);
        $job = Job::firstOrCreate(["name" => "Gerente de Contabilidad"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Sistemas Administrativos Contables (ERP)", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Gerente de Contabilidad"]);
        Experience::create(["job_id" => $job->id, "name" => "Responder auditorías internas (contraloría) y externas (despachos).", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de la Información", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas Contables", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Responder auditorías frente al SAT asertivamente.", "notas" => "Conducirte ante el SAT (cuando si tocar la puerta cuándo no)\n- Qué documentos brindar Qué documentos no.\n- Mucho sentido de estrategia (feeling, experiencia)"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Sentido de Urgencia ", "notas" => "Si hay un buen plan de trabajo, no es necesario tener sentido de urgencia continuamente.\n\nTener bien claro cuando lo bajas y cuando lo subes."]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas Fiscales", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Dominio y Cumplimiento Normativo", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Elaboración e Interpretación de Estados Financieros ", "notas" => "Estados financieros/contables básicos:\n- Estado de Resultados\n- Balance General\n- Flujo de Efectivo\n- Estado de Cambios de Capital"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Toma de Decisiones Asertiva", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Obligaciones Patronales del Seguro Social", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Marco Legal Laboral (bases)", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Contador Jr."]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Atención al detalle ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Contador Jr."]);
        Knowledge::create(["job_id" => $job->id, "name" => "Paquetería Office ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Contador Jr."]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Autodisciplina ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "ERPs de contabilidad (Neodata,Nav y Fortia)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad numérica ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Leyes y Normativas Fiscales", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Cumplimiento de normas ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Portales bancarios ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Optimización del tiempo ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Portal de Secretaría de Administración Tributaria  ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Tolerancia a la presión ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Auxiliar Contable"]);
        $job = Job::firstOrCreate(["name" => "Auxiliar Contable"]);
        $job = Job::firstOrCreate(["name" => "Auxiliar Contable"]);
        $job = Job::firstOrCreate(["name" => "Contador General"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Colaboración con áreas estratégicas/Trabajo en Equipo", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Contador General"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Sistemas Administrativos Contables (ERP)", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Contador General"]);
        Experience::create(["job_id" => $job->id, "name" => "Dar solución al 100% de las observaciones de auditorías internas y externas. ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Habilidad Numérica", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Control y Gestión de Presupuestos", "notas" => "Supervisar que se cumpla en tiempo y forma y generar ahorros."]);
        Experience::create(["job_id" => $job->id, "name" => "Haber presentado reportes de información a la gerencia.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Análisis", "notas" => "No cegarse por la operación, Ojo auditor\nPara obtener información mas confiable"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas Fiscales", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Haber lidereado la migración de un sistema ERP a otro.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de la Información", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas Contables", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Cumplimiento y Dominio Normativo", "notas" => "Normativas internas y externas"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Elaboración e Interpretación de Informes Financieros ", "notas" => "Estados financieros/contables básicos:\n- Estado de Resultados\n- Balance General\n- Flujo de Efectivo\n- Estado de Cambios de Capital"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Optimización del tiempo", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Cuentas por Cobrar y Cuentas por Pagar", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Atención a Auditorias", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Tesorería", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Marco Legal Laboral (bases)", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Excel Intermedio", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Auxiliar Contable"]);
        $job = Job::firstOrCreate(["name" => "Auxiliar Contable"]);
        $job = Job::firstOrCreate(["name" => "Auxiliar Contable"]);
        $job = Job::firstOrCreate(["name" => "Gerente de TI"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Visión Tecnológica ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Gerente de TI"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Elaboración, Manejo y Control de Presupuestos", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Gerente de TI"]);
        Experience::create(["job_id" => $job->id, "name" => "Haber participado en la creación de módulos de plataformas para mejorar procesos.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Innovación y Desarrollo de Procesos Tecnológicos", "notas" => "Liderar el proceso de innovación tecnológica en la organización \nMejora continua, ir viendo más allá de lo que ya existe para mejorarlo."]);
        Knowledge::create(["job_id" => $job->id, "name" => "Softwares de Planificación de Recursos Empresariales", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Haber participado en el desarrollo de módulos para plataformas que involucren transacciones electrónicas (Stripe, PayPal)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de Recursos", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "ITIL (Información Techology Infraestructure Library)", "notas" => "Conjunto de procedimientos que te ayudan a permear ciertos comportamientos en el área para mejorar el servicio. \nAsí como la definición de procesos para la mejora continua. "]);
        Experience::create(["job_id" => $job->id, "name" => "Constante actualización en tecnologías de la información.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de Stakeholders", "notas" => "Involucras a tus usuarios, socios estratégicos y proveedores."]);
        Knowledge::create(["job_id" => $job->id, "name" => "Aplicaciones WEB", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Orientación al Cliente/Servicio ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Administración de Proyectos           ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Equipos de Computación y Software", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Desarrollo de Softwares", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Base de Datos SQL", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Comercio Electrónico", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Marco Legal Laboral (bases)", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Aplicaciones"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Innovación y Desarrollo de Procesos Tecnológicos", "notas" => "Involucra también el mejoramiento Continuo\nActualizaciones en tendencias tecnológicas"]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Aplicaciones"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Administración de Proyectos           ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Aplicaciones"]);
        Experience::create(["job_id" => $job->id, "name" => "Haber optimizado y digitalizado los procesos de un área. ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Orientación al Cliente/Servicio ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Automatización y Digitalización de Procesos Informáticos", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Liderear un proyecto de desarrollo de nuevas aplicaciones de principio a fin.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad Analítica", "notas" => "Capaz de interpretar las solicitudes "]);
        Knowledge::create(["job_id" => $job->id, "name" => "Administración de Proyectos de Desarrollo (Waterfall, Scrum, SDLC)", "notas" => "Metodologías para saber como trabajar los proyectos "]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de Información", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Lenguajes de Programación (.Net, PHP, JavaScript, CSS, HTML) ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de Recursos", "notas" => "Alternativas para el ahorro de recursos"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Business Intelligence y PowerBI", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Web Services ", "notas" => "Mecanismo de conexión de datos"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Herramientas SSIS, SSRS, SSAS", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Manejadores de Bases de Datos (SQL, MySQL)", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Servidores de Aplicación (Apache, IIS)", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Framework de Desarrollo (Laravel, CodeIgniter)", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Arquitectura de Base de Datos", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Procesos de Nómina", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Marco Legal Laboral (bases)", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Analista Jr. de Sistemas de Información"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Respuesta ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Analista Jr. de Sistemas de Información"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Paquetería Office ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Analista Jr. de Sistemas de Información"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Colaboración ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "MS SQL Server ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Retroalimentación y Control ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "IIS (Internet Information Services)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Orientación al Servicio ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Escritorio Remoto", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Mejoramiento Continuo", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "GIT", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Disponibilidad", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "MySQL", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "MS Reporting Service", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Power Bi", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Visual Studio", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Analista Sr. de Sistemas de Información"]);
        $job = Job::firstOrCreate(["name" => "Analista Sr. de Sistemas de Información"]);
        $job = Job::firstOrCreate(["name" => "Analista Sr. de Sistemas de Información"]);
        $job = Job::firstOrCreate(["name" => "Consultor Funcional"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Conocimiento Organizativo", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Consultor Funcional"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Administración de Proyectos           ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Consultor Funcional"]);
        Experience::create(["job_id" => $job->id, "name" => "Haber llevado al menos 3 implementaciones exitosas de ERP.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de Información", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Paquetería Office 365 (bases)", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Gestionar la cartera de proveedores de tecnología de manera eficaz.", "notas" => "Búsqueda\n- Ideas de servicios\n- Cotizaciones \n- Pagos\n- Calidad ofrecida\n- Cumplimiento de entrega"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Pensamiento Crítico", "notas" => "Evaluar la mejor opción para los requerimientos de todas las áreas de la UDN"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Plataformas de Comunicación (bases)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Asesoría y Acompañamiento", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "ERP Dynamics NAV", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de Recursos", "notas" => "Presupuesto definido para el ERP"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Áreas funcionales de la UDN (bases) ", "notas" => "Ejemplo;
Contabilidad, Activo Fijo, Bancos, Cuentas por Cobrar y por Pagar. \nFinancieros, Presupuestos..\nCompras, almacén, producción, clientes, proveedores.."]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Orientación al Cliente/Servicio ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "CMMI, Sure Step  (Metodología de implementación de ERPs)", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Consultor de Implementación"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Ejecutividad", "notas" => "Microsoft Dynamics NAV"]);
        $job = Job::firstOrCreate(["name" => "Consultor de Implementación"]);
        $job = Job::firstOrCreate(["name" => "Consultor de Implementación"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Mejoramiento Continuo ", "notas" => "Microsoft Dynamics AX "]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Orientación a la Calidad ", "notas" => "Microsoft Dynamics 365"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Orientación al Servicio ", "notas" => "SQL"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Análisis", "notas" => "Manejo de ERP"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Resolución de Problemas", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Soporte Tecnico"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Pensamiento Analítico", "notas" => "Pensar con la cabeza fría y con los datos con los que se cuentan.\nY recopilar datos."]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Soporte Tecnico"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Administración de Proyectos", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Soporte Tecnico"]);
        Experience::create(["job_id" => $job->id, "name" => "Gestionar la cartera de proveedores de tecnología de manera eficaz.", "notas" => "Búsqueda\n- Ideas de servicios\n- Cotizaciones \n- Pagos\n- Calidad ofrecida\n- Cumplimiento de entrega"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Prevención de Riesgos", "notas" => "Cambiar la forma para que TI no sea apaga fuegos"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Amazon Web Services", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Haber implementado redes administradas por un servidor de dominio. ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Respuesta y Resolución", "notas" => "Tomando en cuenta las diferencias de las UDN, evaluar que puede funcionar en una y en otra"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Uso y manejo de servidores", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Haber manejado/ implementado enlaces de antenas (microondas).", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Sentido de Urgencia", "notas" => "Priorizar la urgencia de las actividades"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Microsoft Office 365 (Tenant, SP, OneDrive, ATP, Seguridad, etc.)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Orientación al Cliente/Servicio ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Herramientas multimedia de colaboración (Zoom, Teams, Skype, Polycom, Blue Jeans)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Mejoramiento Continuo", "notas" => "De lo que se tiene, que se puede mejorar."]);
        Knowledge::create(["job_id" => $job->id, "name" => "Redes(Switch, routers, Firewall, AP’s, Enlaces de voz y datos, Antenas, Conmutadores)", "notas" => "Diagnosticos"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Data Lost Prevention y Data Recovery Prevention", "notas" => "DLP- Prevención de datos\nDRP- Recuperación de datos"]);
        $job = Job::firstOrCreate(["name" => "Ingeniero de Soporte"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Autosupervisión ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Ingeniero de Soporte"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Suite de Office ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Ingeniero de Soporte"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Coordinación", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Mantenimiento correctivo y preventivo de equipo", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Negociación ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Consola de administración de Office 365", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Orientación de Servicio  ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Sistemas operativos (Windows 7, 8, 8.1 y 10;
Windows server 2008, 2012;
MacOS)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Resolución de Problemas ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Active Directory", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Responsabilidad", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Smartsheet", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Escritorios remotos", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Herramientas para gestión y aplicación de firma electrónica", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "ServiceDesk Plus", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Consola de antivirus", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Especialista en Infraestructura y Ciberseguridad"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Visión Financiera y del Negocio", "notas" => "Perspicacia Financiera"]);
        $job = Job::firstOrCreate(["name" => "Especialista en Infraestructura y Ciberseguridad"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Financieros", "notas" => "Específicos:\n- Proyecciones Financieras\n- Análisis Financieros\n- Evaluación de Proyectos de Inversión\n- Bancos\n- Instrumentos Financieros\n\nBases:\n- Matemáticas Financieras \n- Elaboración y Entendimiento de Estados Financieros\n- Inversiones\n- Presupuestos\n- Seguros de Riesgo\n- Mercado de Derivados"]);
        $job = Job::firstOrCreate(["name" => "Especialista en Infraestructura y Ciberseguridad"]);
        Experience::create(["job_id" => $job->id, "name" => "Desarrollar modelos financieros materializados/ejecutables para los proyectos del Grupo.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Pensamiento Crítico", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Evaluación de Proyectos Financieros /Construcción y Análisis de Modelos Financieros ", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Lograr un otorgamiento de crédito por parte de alguna institución financiera (Banobras...)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de la Información", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Administración de Proyectos", "notas" => "Definición y presentación del proyecto \nPlanificación \nEstablecer objetivos\nSupervisión de tareas\nImplementación de soluciones o cambios"]);
        Experience::create(["job_id" => $job->id, "name" => "Elaborar y presentar los proyectos y modelos financieros para dirección y sus avances.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Análisis", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Excel Avanzado", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Respuesta y Resolución", "notas" => "Cumplir con los tiempos de entrega (resolver problemas Para que salga todo adelante)\n- Flexibilidad y Adaptación al Cambio\n- Disponibilidad de tiempo\n- Autosupervisión"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Marco Legal Laboral (bases)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Colaboración con áreas estratégicas/Trabajo en Equipo", "notas" => "Mantener alianzas estratégicas para el logro de objetivos: TI, Contabilidad, Administración, etc.\n(tanto interna como externa)"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Construcción de Relaciones", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Bienestar"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Pensamiento Analítico y Estratégico", "notas" => "Analizar información para evaluar el impacto. Para la creación de estrategias "]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Bienestar"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Elaboración, Manejo y Control de Presupuestos", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Bienestar"]);
        Experience::create(["job_id" => $job->id, "name" => "Liderear un DVR y Posada", "notas" => "Creación del concepto \n- Planeación\n- Ejecución \n- Solución de Problemas"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Creatividad e Innovación", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Ortografía y Redacción", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Haber diseñado el plan anual del área, cumpliendo con las siguientes características: innovador, acorde a las tendencias, necesidades y cultura del Grupo.", "notas" => "Indicadores Presupuesto\nActividades"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Orientación al Cliente/Servicio ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Prácticas de Bienestar/Psicología Positiva", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Haber realizado visitas de diálogo con directores y llamadas de bienestar.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Atención al Detalle ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas en Bienestar (NOM035-NOM030)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de Recursos", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Tendencias afines al área", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Colaboración /Trabajo en Equipo", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Logística de Eventos ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Dominio y Cumplimiento Normativo", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Mercadotecnia y Diseño", "notas" => "Diseño de Imagen (alineada al negocio)\nMedios de Comunicación\nEstrategias Digitales\nTener presencia y que transmita"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Leyes y Normativas Laborales", "notas" => "LEY FEDERAL DEL TRABAJO\n- LEY DEL SEGURO SOCIAL (Obligaciones Patronales y Empleados)\n- LEY ISR- NORMATIVAS FISCALES (noción básica)\n- Cumplimiento de requisitos ante dependencias: STPS, IMSS, INFONAVIT, FONACOT (nociones básicas)"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Administración de Proyectos", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Definición y Evaluación de KPIs de Bienestar", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Gestora de Bienestar y Eventos"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Atención al Detalle ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Gestora de Bienestar y Eventos"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Paquetería Office ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Gestora de Bienestar y Eventos"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Creatividad ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Photoshop", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Destreza Comunicativa", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Organización de eventos ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Impacto e Influencia ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Redacción y Ortografía", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Planificación y Organización", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Relaciones publicas ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de Recursos ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Gestora de Bienestar y Programas"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Atención al Detalle", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Gestora de Bienestar y Programas"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Logística de eventos.", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Gestora de Bienestar y Programas"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Compromiso con la Organización", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Relaciones públicas y  comunicación. ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Creatividad ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Área de bienestar.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de Recursos", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Manejo de base de datos.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Innovación ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Orientación al Servicio ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Desarrollo Organizacional"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Pensamiento Analítico y Estratégico", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Desarrollo Organizacional"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Elaboración, Manejo y Control de Presupuestos", "notas" => "Nómina\n- del área de CH"]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Desarrollo Organizacional"]);
        Experience::create(["job_id" => $job->id, "name" => "Realizar y dar seguimiento al cumplimiento de los objetivos y plan anual del área (D.O.;
Comunicación y Cultura)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Mejoramiento Continuo / Orientación a la Calidad", "notas" => "Mejora de procesos e indicadores para brindar un mejor servicio"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Modelo de Competencias", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Gestionar el proceso integral de (Evaluación de Desempeño, Potencial, Retroalimentación y Planes de Desarrollo)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Orientación al Cliente/Servicio ", "notas" => "Saber comunicarnos de manera efectiva de acuerdo al nivel, "]);
        Knowledge::create(["job_id" => $job->id, "name" => "Evaluaciones de Desempeño y Potencial", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Llevar a cabo Intervenciones para mejorar el desempeño ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Atención al Detalle ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Planes de Desarrollo", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Creación de instrumentos para el D.O. ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de Recursos", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Cultura Organizacional", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Colaboración /Trabajo en Equipo", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Comunicación Organizacional ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Dominio y Cumplimiento Normativo", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas en Bienestar (NOM035-NOM030)", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Leyes y Normativas Laborales", "notas" => "LEY FEDERAL DEL TRABAJO\n- LEY DEL SEGURO SOCIAL (Obligaciones Patronales y Empleados)\n- LEY ISR- NORMATIVAS FISCALES (noción básica)\n- Cumplimiento de requisitos ante dependencias: STPS, IMSS, INFONAVIT, FONACOT (nociones básicas)"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Administración de Proyectos", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Definición y Evaluación de KPIs de DO", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Analista Sr. de Capacitación y Desarrollo"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Pensamiento Crítico ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Analista Sr. de Capacitación y Desarrollo"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Paquetería Office ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Analista Sr. de Capacitación y Desarrollo"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Visión global ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Modelo de Competencias ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Planificación y Organización", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Evaluaciones de Desempeño y Potencial", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Orientación al Cliente - Enfoque al Cliente", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Detección de Necesidades de Capacitación  ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Proactividad (iniciativa) - Empuje para conseguir resultados", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Planes de Desarrollo", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Dominio y Cumplimiento Normativo", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Cultura Organizacional", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Asesorar", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Requerimientos de STPS", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de la Información", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Prevención de Problemas", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Promotor de Cultura", "notas" => ""]);
    }
}
