<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Experience;
use App\Models\Job;
use App\Models\JobCompetence;
use App\Models\Knowledge;

class METAPuestosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $job = Job::firstOrCreate(["name" => "Director de META"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de Recursos", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Director de META"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Financieros", "notas" => "Matemáticas Financieras\n- Evaluación de Proyectos Financieros\n- Entendimiento de Estados Financieros\n- Inversiones\n- Presupuestos"]);
        $job = Job::firstOrCreate(["name" => "Director de META"]);
        Experience::create(["job_id" => $job->id, "name" => "Tener éxito en negociaciones estratégicas de alto impacto (internas y externas)", "notas" => "Internas: entre áreas\n- Externas: bancos, cámaras/asociaciones, clientes, proveedores"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión del Riesgo", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas Contables ", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Liderar con éxito equipos de alto desempeño", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Sentido de Urgencia", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas Fiscales ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Orientación al Cliente/Servicio", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas y Sistemas de Gestión de Calidad", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Legal (bases)", "notas" => "Contractual\n- Entendimiento de los temas legales para identificar si puede existir algún problema, siempre apoyándose del abogado para prevenirlos y solucionarlos."]);
        Knowledge::create(["job_id" => $job->id, "name" => "Desarrollo de Infraestructura", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Concesiones Carreteras", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativa SCT", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Administración de Proyectos", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Marco Legal Laboral (bases)", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Inglés (avanzado)", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Asistente de Dirección"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Administración de la confianza ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Asistente de Dirección"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Paquetería Microsoft Office ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Asistente de Dirección"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Disponibilidad ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Protocolo de eventos y reuniones empresariales", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Adaptabilidad ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Manejo de agenda ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de coordinación", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Colaboración ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Comunicación escrita", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Sistemas de Gestión Integral"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Cumplimiento y Dominio Normativo", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Sistemas de Gestión Integral"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas y Sistemas de Gestión de Calidad ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Sistemas de Gestión Integral"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Análisis", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas y Sistemas de Gestión Ambiental", "notas" => "ISO de medio ambiente"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Asesoría y Acompañamiento", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativa y Legislación Ambiental", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Mejoramiento Continuo / Orientación a la Calidad", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Sistema de Seguridad Vial", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Colaboración con áreas estratégicas/Trabajo en Equipo", "notas" => "Mantener alianzas estratégicas para el logro de objetivos con todas las áreas"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativa SCT", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Marco Legal Laboral (bases)", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Compras"]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Compras"]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Compras"]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Comercialización"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de respuesta", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Comercialización"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Mercadotecnia", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Comercialización"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de recursos", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Multimedios", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Orientación al servicio", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Servicio al cliente", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Pensamiento estratégico", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Infraestructura carretera", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Atención al detalle ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Comunicación", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Construcción de relaciones", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Creatividad ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Seguridad"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Ejecutividad", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Seguridad"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Defensa Personal", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Seguridad"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de Riesgos", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Estrategias de seguridad y vigilancia ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Asesoría y Acompañamiento", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Leyes y Normativas del Sistema Penal Acusatoria y del Primer Respondiente", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Respuesta", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas y Sistemas de Gestión de Calidad ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Dominio y Cumplimiento Normativo", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Marco Legal Laboral (bases)", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Gerente Administrativo"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Visión Financiera y del Negocio", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Gerente Administrativo"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Sistemas Administrativos Contables (ERP)", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Gerente Administrativo"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión del Riesgo", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas Contables", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de la Información", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas Fiscales", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de Recursos", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Elaboración e Interpretación de Estados Financieros ", "notas" => "Estados financieros/contables básicos:\n- Estado de Resultados\n- Balance General\n- Flujo de Efectivo\n- Estado de Cambios de Capital"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Sentido de Urgencia", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Elaboración, Manejo y Control de Presupuestos", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Dominio y Cumplimiento Normativo", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Administración de Nóminas (IMSS, INFONAVIT, FONACOT...)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Anticipación de Problemas", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Manejo de Bancos, Créditos Bancarios.. ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Toma de Decisiones Asertiva", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Marco Legal (bases)", "notas" => "Corporativo\n- Laboral: Para que la empresa pueda operar sin problema"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Marco Legal Laboral (bases)", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Excel Intermedio", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Auditor"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Acatamiento de valores ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Auditor"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Paqueteria Office ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Auditor"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Atención al detalle ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Leyes y normativa relacionada a la Secretaría de Comunicaciones y Transporte", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de investigación ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Finanzas", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Precisión ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Contabilidad ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Conocimiento organizativo ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Criterio ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Gerente de Contraloría"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Visión Financiera y del Negocio", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Gerente de Contraloría"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Softwares de contabilidad (ERP)", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Gerente de Contraloría"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión del Riesgo", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normatividad Financiera (IFRS y NIFS)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de la Información", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Elaboración e Interpretación de Informes Financieros ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de Recursos", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Leyes y Normativas Laborales", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Sentido de Oportunidad", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Obligaciones Patronales del Seguro Social", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Sentido de Urgencia", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Marco Legal Laboral (bases)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Dominio y Cumplimiento Normativo", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Contador General"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Colaboración con áreas estratégicas/Trabajo en Equipo", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Contador General"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Sistemas Administrativos Contables (ERP)", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Contador General"]);
        Experience::create(["job_id" => $job->id, "name" => "Cumplimiento del presupuesto a ejercer, generando ahorros.", "notas" => "Acompañamiento y seguimiento con las áreas para que se cumpla (brindando tips sobre cómo lograrlo)"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Habilidad Numérica", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Control y Gestión de Presupuestos", "notas" => "Supervisar que se cumpla en tiempo y forma y generar ahorros."]);
        Experience::create(["job_id" => $job->id, "name" => "Dar solución al 100% de las observaciones de contraloría.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Análisis", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Administración de bienes materiales y no materiales", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Migrar la información de un sistema administrativo contable a otro en tiempo y forma.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de la Información", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas Contables", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Dominio y Cumplimiento Normativo", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Cuentas por Cobrar y Cuentas por Pagar", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Optimización del tiempo", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Tesorería", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Excel Intermedio", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Marco Legal Laboral (bases)", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Elaboración e Interpretación de Informes Financieros ", "notas" => "Estados financieros/contables básicos:\n- Estado de Resultados\n- Balance General\n- Flujo de Efectivo\n- Estado de Cambios de Capital"]);
        $job = Job::firstOrCreate(["name" => "Encargado de Almacen"]);
        $job = Job::firstOrCreate(["name" => "Encargado de Almacen"]);
        $job = Job::firstOrCreate(["name" => "Encargado de Almacen"]);
        $job = Job::firstOrCreate(["name" => "Analista Jr. de Capital Humano"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Comunicación efectiva", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Analista Jr. de Capital Humano"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Paqueteria Office ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Analista Jr. de Capital Humano"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de investigación", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Fortia ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de evaluación ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Plataformas de reclutamiento", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de talento ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Leyes y normativas relacionadas a la gestión de personal", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Orientación al servicio ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Gestión por competencias ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de negociación ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Técnicas de la entrevista", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Contador IFRS"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Colaboración con áreas estratégicas/Trabajo en Equipo", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Contador IFRS"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Sistemas Administrativos Contables (ERP)", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Contador IFRS"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Habilidad Numérica", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas Contables", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Análisis", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas Fiscales", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de la Información", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Elaboración e Interpretación de Informes Financieros ", "notas" => "Estados financieros/contables básicos:\n- Estado de Resultados\n- Balance General\n- Flujo de Efectivo\n- Estado de Cambios de Capital"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Dominio y Cumplimiento Normativo", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Atención a Auditorias", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Optimización del tiempo", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Marco Legal Laboral (bases)", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Auxiliar Contable"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Colaboración", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Auxiliar Contable"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Paquetería Microsoft Office ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Auxiliar Contable"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Tolerancia a la frustración", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Softwares de contabilidad ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad numérica", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Leyes fiscales ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de análisis ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normas Internacionales de Información Financiera (IFRS) ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Optimización del tiempo ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Reformas Fiscales", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Atención al detalle", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Declaraciones anuales", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Resolución de miscelánea fiscal ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Coordinador NIFS"]);
        $job = Job::firstOrCreate(["name" => "Coordinador NIFS"]);
        $job = Job::firstOrCreate(["name" => "Coordinador NIFS"]);
        $job = Job::firstOrCreate(["name" => "Tesorera"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de negociación ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Tesorera"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Paquetería Office ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Tesorera"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad numérica", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "ERP", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Pensamiento estratégico ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Portales bancarios", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de información ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Toma de decisiones ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de recursos ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Gerente Administrativo"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Respuesta y Resolución", "notas" => "Disponibilidad\nDar respuesta en tiempo y forma."]);
        $job = Job::firstOrCreate(["name" => "Gerente Administrativo"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Elaboración, Manejo y Control de Presupuestos", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Gerente Administrativo"]);
        Experience::create(["job_id" => $job->id, "name" => "Experiencia en operación y conservación de carreteras.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Mejoramiento Continuo/ Orientación a la Calidad", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas y Sistemas de Gestión de Calidad", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Experiencia en sistemas de peaje y telepeaje.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Orientación al Cliente/Servicio ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativa SCT", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Experiencia en resolución de conflictos con grupos (Transportistas, ejidatarios, etc.)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Construcción de Relaciones ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Tecnologías en Peaje y Telepeaje", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Visitas a otras autopistas;
Tener comunicación y benchmarking con puestos similares en el mercado;
conocer las tendencias y las mejores prácticas que existen (exposure).", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de Recursos", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Operación de Autopistas", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Dominio y Cumplimiento Normativo", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Seguridad Vial ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Seguridad Patrimonial", "notas" => "Alineado a los procesos de calidad.\nControl del recurso."]);
        Knowledge::create(["job_id" => $job->id, "name" => "Administración de Proyectos           ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Marco Legal Laboral (bases)", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Analista Sr. Liquidador"]);
        $job = Job::firstOrCreate(["name" => "Analista Sr. Liquidador"]);
        $job = Job::firstOrCreate(["name" => "Analista Sr. Liquidador"]);
        $job = Job::firstOrCreate(["name" => "Auxiliar de Liquidación"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Atención al Detalle", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Auxiliar de Liquidación"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Paquetería Office ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Auxiliar de Liquidación"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad Numérica", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Sistema de Telepeaje ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Cumplimiento de Normas", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Norma ISO 9001 (Sistema de Gestión de la Calidad – SGC)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Precisión ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Norma ISO 14001 (Sistema de Gestión Ambiental – SGA)", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Norma ISO 39001 (Sistema de Gestión de Seguridad Vial -SV)", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Seguridad"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Ejecutividad", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Seguridad"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Defensa Personal", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Seguridad"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de Riesgos", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Estrategias de seguridad y vigilancia ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Asesoría y Acompañamiento", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Leyes y Normativas del Sistema Penal Acusatoria y del Primer Respondiente", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Respuesta", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Dominio y Cumplimiento Normativo", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Jefe de Operación"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Orientación al Cliente/Servicio ", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Jefe de Operación"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Software de Liquidación", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Jefe de Operación"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Orientación a la Calidad", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas y Sistemas de Gestión de Calidad ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de Recursos", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Manejo de Efectivo", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Respuesta", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Clasificación de ejes y clases", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Polifuncionalidad", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Identificación de Billetes Falsos", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Marco Legal Laboral (bases)", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Gerente de Mantenimiento"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de Recursos", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Gerente de Mantenimiento"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Elaboración, Manejo y Control de Presupuestos", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Gerente de Mantenimiento"]);
        Experience::create(["job_id" => $job->id, "name" => "Participar en proyectos de construcción de carreteras y vías terrestres.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Dominio y Cumplimiento Normativo", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Costos/ Mercadeo", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Liderar los mantenimientos de carreteras y vías terrestres.", "notas" => "Tener la autopista en excelentes condiciones de mantenimiento, seguridad y operación en beneficio de los usuarios. "]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Toma de Decisiones Asertiva", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normatividad en Construcción de Carreteras (SCT)", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Manejo adecuado de la relación con el cliente (SCT...)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Respuesta y Resolución", "notas" => "Disponibilidad\nDar respuesta en tiempo y forma.\nNo solo a la empresa, sino tambien ante el cliente y las diversidad dependencias;y/o ante cualquier contingencia.\nEj. SCT"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas y Sistemas de Gestión de Calidad ", "notas" => ""]);
        Experience::create(["job_id" => $job->id, "name" => "Hacerse cargo de los reportes mensuales y trimestrales para SCT y Fideicomiso.", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Mejoramiento Continuo/ Orientación a la Calidad", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Leyes y Normativas de Vialidad", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Mantenimiento de Vías Terrestres", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Concreto, Pavimentos y Estructuras", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Softwares de Diseño", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Administración de Proyectos", "notas" => "Planeación / Desarrollo / Diseño\nEjecución\nSeguimiento\nControl\nEntrega"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Marco Legal Laboral (bases)", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Mantenimiento"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Capacidad de Respuesta y Resolución", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Mantenimiento"]);
        Knowledge::create(["job_id" => $job->id, "name" => "Manejo y Control de Presupuestos", "notas" => ""]);
        $job = Job::firstOrCreate(["name" => "Coordinador de Mantenimiento"]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Mejoramiento Continuo / Orientación a la Calidad", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Administración y Control de Proyectos ", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Dominio y Cumplimiento Normativo", "notas" => "Normativa de SCT \nNorma Oficial Mexicana \nISO "]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normatividad en Construcción de Carreteras (Normativa SCT)", "notas" => ""]);
        JobCompetence::create(["job_id" => $job->id, "name" => "Gestión de Recursos", "notas" => "Optimización de recursos para obtener ahorros "]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas de Vialidad", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Mantenimiento de Vías Terrestres", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Concreto, Pavimentos, Estructuras, Estabilización de Taludes y Cortes", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Normativas y Sistemas de Gestión de Calidad ", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => "Softwares de Diseño", "notas" => ""]);
        Knowledge::create(["job_id" => $job->id, "name" => " Marco Legal Laboral (bases)", "notas" => ""]);
    }
}
