<?php

namespace Database\Seeders;

use App\Models\Departamento;
use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Job;
use App\Models\Profile;
use App\Models\Udn;
use App\Models\Level;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // $this->disableForeign();
        $this->import();
        // $this->enableForeign();
    }


    protected function disableForeign()
    {
        Schema::table('profiles', function (Blueprint $table) {
            $table->dropForeign('profiles_report_to_foreign');
        });
    }

    protected function enableForeign()
    {
        Schema::table('profiles', function (Blueprint $table) {
            $table->foreign('report_to')->references('id')->on('profiles');
        });
    }


    protected function import()
    {
        $data = [
            ['username' => 'Vicente Rangel Mancilla', 'report_id' => '1', 'puesto' => 'Presidente', 'report_to' => null, 'udn' => 'SLP-Corpo', 'nivel' => 'Presidente', 'correo' => '', 'TC' => '', 'PC' => '','num_nomina'=>'NULL','departamento'=>'DG','password' => 'Qo7Wk5Dz5Lc'],
['username' => 'Jose Alejandro Leura Gutierrez', 'report_id' => '2', 'puesto' => 'Superintendente', 'report_to' => 126, 'udn' => 'SLP-Plaza', 'nivel' => 'Coordinador C/PA', 'correo' => 'AlejandroLeura@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8006','departamento'=>'OPERACIONES','password' => 'Iw5Te5Fr8Ti'],
['username' => 'Javier Arteaga Barcenas', 'report_id' => '3', 'puesto' => 'Coordinador De Infraestructura', 'report_to' => 126, 'udn' => 'SLP-Plaza', 'nivel' => 'Coordinador S/PA', 'correo' => 'JavierArteaga@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8010','departamento'=>'OPERACIONES','password' => 'Yi3Jr5Ru3Js'],
['username' => 'Abraham Baez Medellin', 'report_id' => '4', 'puesto' => 'Lider De Proyecto', 'report_to' => 2, 'udn' => 'SLP-Plaza', 'nivel' => 'Coordinador S/PA', 'correo' => 'AbrahamBaez@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8012','departamento'=>'OPERACIONES','password' => 'Sa0Xk7Qi5Fx'],
['username' => 'Judith Vazquez Martinez', 'report_id' => '5', 'puesto' => 'Gestor De Créditos', 'report_to' => 12, 'udn' => 'SLP-Plaza', 'nivel' => 'Especialista S/PA', 'correo' => 'JudithVazquez@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8017','departamento'=>'COMERCIAL','password' => 'Eh5Mq9Bt0Rt'],
['username' => 'Gilberto Ojeda Chavarria', 'report_id' => '6', 'puesto' => 'Coordinador Técnico', 'report_to' => 126, 'udn' => 'SLP-Plaza', 'nivel' => 'Coordinador C/PA', 'correo' => 'GilbertoOjeda@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8022','departamento'=>'OPERACIONES','password' => 'Qb4Jf5Rv0Um'],
['username' => 'Estuardo Antonio Molina Martinez', 'report_id' => '7', 'puesto' => 'Coordinador De Postventa', 'report_to' => 126, 'udn' => 'SLP-Plaza', 'nivel' => 'Coordinador C/PA', 'correo' => 'EstuardoMolina@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8028','departamento'=>'OPERACIONES','password' => 'Dg8Mr2Fa1Gc'],
['username' => 'Gerardo Ortega Tristan', 'report_id' => '8', 'puesto' => 'Lider De Proyecto', 'report_to' => 2, 'udn' => 'SLP-Plaza', 'nivel' => 'Coordinador C/PA', 'correo' => 'GerardoOrtega@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8037','departamento'=>'OPERACIONES','password' => 'Tb2Ht2Um5Qz'],
['username' => 'Fernando Juache Diaz', 'report_id' => '9', 'puesto' => 'Supervisor De Edificación', 'report_to' => 8, 'udn' => 'SLP-Plaza', 'nivel' => 'Especialista S/PA', 'correo' => 'FernandoJuache@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8047','departamento'=>'OPERACIONES','password' => 'Qg3Un7Tt6Ra'],
['username' => 'Alejandro Gonzalez Rangel', 'report_id' => '10', 'puesto' => 'Gerente De Proyecto Ximonco', 'report_to' => 126, 'udn' => 'SLP-Plaza', 'nivel' => 'Gerente S/PA', 'correo' => 'AlejandroGonzalez@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8181','departamento'=>'OPERACIONES','password' => 'Uk7Tc8Ni0Np'],
['username' => 'Katia Montserrat Arroyo Moran', 'report_id' => '11', 'puesto' => 'Auxiliar Técnico', 'report_to' => 6, 'udn' => 'SLP-Plaza', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'KatiaArroyo@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8195','departamento'=>'OPERACIONES','password' => 'Xb2Hc6Zd3Dx'],
['username' => 'Manuel Alejandro Martinez Guevara', 'report_id' => '12', 'puesto' => 'Coordinador De Ventas', 'report_to' => 126, 'udn' => 'SLP-Plaza', 'nivel' => 'Coordinador C/PA', 'correo' => 'AlejandroMartinez@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8201','departamento'=>'COMERCIAL','password' => 'Wt6Xk3Qp1It'],
['username' => 'Diana Maria Palacios Quiroga', 'report_id' => '13', 'puesto' => 'Coordinador Administrativo', 'report_to' => 126, 'udn' => 'SLP-Plaza', 'nivel' => 'Coordinador S/PA', 'correo' => 'DianaPalacios@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8244','departamento'=>'ADMON','password' => 'Px2Ci5Pa8As'],
['username' => 'Ricardo Martinez Regalado', 'report_id' => '14', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 12, 'udn' => 'SLP-Plaza', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'RicardoMartinez@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8285','departamento'=>'COMERCIAL','password' => 'Ur6Ml1Qb4St'],
['username' => 'Leticia Del Rocio Martinez Gutierrez', 'report_id' => '15', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 12, 'udn' => 'SLP-Plaza', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'rociomartinez@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8296','departamento'=>'COMERCIAL','password' => 'Ou8Er9Ot7Iw'],
['username' => 'Rosa Isela Guevara Martinez', 'report_id' => '16', 'puesto' => 'Coordinador De Ventas', 'report_to' => 82, 'udn' => 'Aguascalientes', 'nivel' => 'Coordinador C/PA', 'correo' => 'IselaGuevara@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'17005','departamento'=>'COMERCIAL','password' => 'Mm8Ik9Vn8Rn'],
['username' => 'Gabriela Guadalupe Esquivel Rodriguez', 'report_id' => '17', 'puesto' => 'Supervisor De Postventa', 'report_to' => 7, 'udn' => 'SLP-Plaza', 'nivel' => 'Especialista S/PA', 'correo' => 'GabrielaEsquivel@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8320','departamento'=>'OPERACIONES','password' => 'Qa7Em0Gl2Jn'],
['username' => 'Jose Agustin Salazar Sanchez', 'report_id' => '18', 'puesto' => 'Lider De Proyecto', 'report_to' => 2, 'udn' => 'SLP-Plaza', 'nivel' => 'Coordinador S/PA', 'correo' => 'josesalazar@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8077','departamento'=>'OPERACIONES','password' => 'Ms6Ud3Hu9Vi'],
['username' => 'Alejandro Candelaria Santiago', 'report_id' => '19', 'puesto' => 'Integrador De Expedientes', 'report_to' => 5, 'udn' => 'SLP-Plaza', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'AlejandroSantiago@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8406','departamento'=>'COMERCIAL','password' => 'Ky8Ay6Dt0Px'],
['username' => 'Carlos Velazquez Moreno', 'report_id' => '20', 'puesto' => 'Coordinador Técnico', 'report_to' => 82, 'udn' => 'Aguascalientes', 'nivel' => 'Coordinador S/PA', 'correo' => 'carlosvelazquez@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8001','departamento'=>'OPERACIONES','password' => 'Zz7Vz2Qe1Zh'],
['username' => 'Liuva Felisa Cruz Aquino', 'report_id' => '21', 'puesto' => 'Coordinador De Ventas', 'report_to' => 82, 'udn' => 'Aguascalientes', 'nivel' => 'Coordinador S/PA', 'correo' => 'LiuvaCruz@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8402','departamento'=>'COMERCIAL','password' => 'Sl5Gf5Vz4Gc'],
['username' => 'Miguel Angel Gonzalez Padilla', 'report_id' => '22', 'puesto' => 'Supervisor De Obra', 'report_to' => 25, 'udn' => 'Aguascalientes', 'nivel' => 'Especialista S/PA', 'correo' => 'MiguelGonzalezP@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8168','departamento'=>'OPERACIONES','password' => 'Dz7Ip3Kv0Pm'],
['username' => 'Minerva Rosaura Lara Lara', 'report_id' => '23', 'puesto' => 'Gestor De Créditos', 'report_to' => 21, 'udn' => 'Aguascalientes', 'nivel' => 'Especialista S/PA', 'correo' => 'MinervaLara@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8300','departamento'=>'COMERCIAL','password' => 'Vr3Sb0Ub3Hd'],
['username' => 'Jose Luis Chiquito Cruz', 'report_id' => '24', 'puesto' => 'Lider De Proyecto', 'report_to' => 82, 'udn' => 'Aguascalientes', 'nivel' => 'Coordinador S/PA', 'correo' => 'LuisChiquito@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8377','departamento'=>'OPERACIONES','password' => 'Gy8Ql0Mw3Ig'],
['username' => 'Ismael Roberto Davila Perez', 'report_id' => '25', 'puesto' => 'Lider De Proyecto', 'report_to' => 82, 'udn' => 'Aguascalientes', 'nivel' => 'Coordinador C/PA', 'correo' => 'IsmaelDavila@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8393','departamento'=>'OPERACIONES','password' => 'Tc2Mf1Zy6Ro'],
['username' => 'Natyeli Ojeda Samano', 'report_id' => '26', 'puesto' => 'Coordinador Técnico-Administrativo', 'report_to' => 28, 'udn' => 'Celaya', 'nivel' => 'Coordinador S/PA', 'correo' => 'natyeliojeda@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8132','departamento'=>'ADMON - OP','password' => 'Pe5Fw5Hy5Id'],
['username' => 'Adriana Renata Alcantar Perez', 'report_id' => '27', 'puesto' => 'Supervisor De Postventa', 'report_to' => 28, 'udn' => 'Celaya', 'nivel' => 'Especialista S/PA', 'correo' => 'RenataAlcantar@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8271','departamento'=>'OPERACIONES','password' => 'Tl5Yw7Dn7Tg'],
['username' => 'Antonio Jimenez Aranda', 'report_id' => '28', 'puesto' => 'Director De Plaza', 'report_to' => 68, 'udn' => 'Celaya', 'nivel' => 'Director C/PA', 'correo' => 'AntonioJimenez@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8399','departamento'=>'DG','password' => 'Nh8Yn0Qs7Vg'],
['username' => 'Raul Alejandro Cabrera Tejeda', 'report_id' => '29', 'puesto' => 'Lider De Proyecto', 'report_to' => 88, 'udn' => 'Celaya', 'nivel' => 'Coordinador S/PA', 'correo' => 'RaulCabrera@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8400','departamento'=>'OPERACIONES','password' => 'Ip3Zy8Gq7Aa'],
['username' => 'Ma. Guadalupe Melendez Oviedo', 'report_id' => '30', 'puesto' => 'Gerente De Tesorería', 'report_to' => 33, 'udn' => 'SLP-Corpo', 'nivel' => 'Gerente C/PA', 'correo' => 'GuadalupeMelendez@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8003','departamento'=>'DAF','password' => 'Sf3Zj4Sp9Yv'],
['username' => 'Martha Leticia Hernandez Acosta', 'report_id' => '31', 'puesto' => 'Gerente De Capital Humano', 'report_to' => 33, 'udn' => 'SLP-Corpo', 'nivel' => 'Gerente C/PA', 'correo' => 'MarthaHernandez@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8048','departamento'=>'DAF-CH','password' => '66mF!u9Wvw&'],
['username' => 'Gabriela Elizabeth Palomo Zuñiga', 'report_id' => '32', 'puesto' => 'Gerente De Contabilidad Financiera', 'report_to' => 33, 'udn' => 'SLP-Corpo', 'nivel' => 'Gerente C/PA', 'correo' => 'GabrielaPalomo@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8049','departamento'=>'DAF','password' => 'Qz8Go2Ji1Uw'],
['username' => 'Sebastian Andres Ferrari Bordino', 'report_id' => '33', 'puesto' => 'Dirección de Administración y Finanzas', 'report_to' => 68, 'udn' => 'SLP-Corpo', 'nivel' => 'Director C/PA', 'correo' => 'SebastianFerrari@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8053','departamento'=>'DAF','password' => 'Wk$x28X7EHl'],
['username' => 'Sandra Fabiola Ortiz Gonzalez', 'report_id' => '34', 'puesto' => 'Gerente Administrativo', 'report_to' => 32, 'udn' => 'SLP-Corpo', 'nivel' => 'Gerente S/PA', 'correo' => 'FabiolaOrtiz@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8057','departamento'=>'DAF','password' => 'Wg4Gr8No0Wg'],
['username' => 'Alberto Angel Reyna Fuentes', 'report_id' => '35', 'puesto' => 'Coordinador De Infraestructura TI', 'report_to' => 36, 'udn' => 'SLP-Corpo', 'nivel' => 'Coordinador C/PA', 'correo' => 'AlbertoReyna@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8084','departamento'=>'DAF-TI','password' => 'If3Zm3If2Er'],
['username' => 'Luis Fernando Michael Chavez Beltran', 'report_id' => '36', 'puesto' => 'Coordinador de TI', 'report_to' => 33, 'udn' => 'SLP-Corpo', 'nivel' => 'Coordinador C/PA', 'correo' => 'LuisChavez@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8085','departamento'=>'DAF-TI','password' => 'Hv2Sx0Sx7Wk'],
['username' => 'Edna Thalia Uribe Guevara', 'report_id' => '37', 'puesto' => 'Asistente De Dirección', 'report_to' => 68, 'udn' => 'SLP-Corpo', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'EdnaUribe@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8099','departamento'=>'DAF','password' => 'Qj0Qi0Mf4Ko'],
['username' => 'Cristian Lopez Contreras', 'report_id' => '38', 'puesto' => 'Analista de Infraestructura TI', 'report_to' => 35, 'udn' => 'SLP-Corpo', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'CristianLopez@Valoran.onmicrosoft.com', 'TC' => '', 'PC' => '','num_nomina'=>'8191','departamento'=>'DAF-TI','password' => 'Fw6Gz9Ds4Jc'],
['username' => 'Lourdes Larios Lopez', 'report_id' => '39', 'puesto' => 'Jefe de Tesorería', 'report_to' => 30, 'udn' => 'SLP-Corpo', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'lourdeslarios@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8221','departamento'=>'DAF','password' => 'Os1Fs8Ie0Ai'],
['username' => 'Araceli Rodriguez Gomez', 'report_id' => '40', 'puesto' => 'Jefe De Atracción De Talento y Relaciones Laborales', 'report_to' => 31, 'udn' => 'SLP-Corpo', 'nivel' => 'Especialista S/PA', 'correo' => 'AraceliRodriguez@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8311','departamento'=>'DAF-CH','password' => 'Wb6Us0Uz7Hw'],
['username' => 'Alba Estefania Cervantes Torres', 'report_id' => '41', 'puesto' => 'Auxiliar Financiero', 'report_to' => 42, 'udn' => 'SLP-Corpo', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'AlbaCervantes@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8384','departamento'=>'DAF','password' => 'Dc1Oi1Sl5Qg'],
['username' => 'Gerente De Finanzas Y Contraloría', 'report_id' => '42', 'puesto' => 'Gerente De Finanzas Y Contraloría', 'report_to' => 33, 'udn' => 'SLP-Corpo', 'nivel' => 'Gerente C/PA', 'correo' => '', 'TC' => '', 'PC' => '','num_nomina'=>'NULL','departamento'=>'DAF','password' => 'Zv3Vc0Pt5Ma'],
['username' => 'Angel Eleyson Ruiz Mendoza', 'report_id' => '43', 'puesto' => 'Coordinador De Finanzas Y Contraloría', 'report_to' => 33, 'udn' => 'SLP-Corpo', 'nivel' => 'Coordinador C/PA', 'correo' => 'angelruiz@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8122','departamento'=>'DAF','password' => 'Oe3Cr7Ar5Oa'],
['username' => 'Luis Eduardo Loredo Tovar', 'report_id' => '44', 'puesto' => 'Desarrollador Full Stack', 'report_to' => 36, 'udn' => 'SLP-Corpo', 'nivel' => 'Especialista S/PA', 'correo' => 'EduardoLoredo@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8200','departamento'=>'DAF-TI','password' => 'R4nm4n'],
['username' => 'Rodrigo Romero Alvarez', 'report_id' => '45', 'puesto' => 'Coordinador Administrativo', 'report_to' => 48, 'udn' => 'Queretaro', 'nivel' => 'Coordinador C/PA', 'correo' => 'RodrigoRomero@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8016','departamento'=>'ADMON','password' => 'Oh0Nd8My9Jp'],
['username' => 'Jose Estanislao Silva Villarreal', 'report_id' => '46', 'puesto' => 'Superintendente', 'report_to' => 48, 'udn' => 'Queretaro', 'nivel' => 'Coordinador C/PA', 'correo' => 'JoseSilva@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8027','departamento'=>'OPERACIONES','password' => 'Wl3Uw4Ml2Rr'],
['username' => 'Eduardo Martinez Gallegos', 'report_id' => '47', 'puesto' => 'Coordinador Técnico', 'report_to' => 48, 'udn' => 'Queretaro', 'nivel' => 'Coordinador S/PA', 'correo' => 'EduardoMartinez@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8044','departamento'=>'OPERACIONES','password' => 'Lq5Lb9Np6Im'],
['username' => 'Franscisco Javier Rodriguez Alvarez Malo', 'report_id' => '48', 'puesto' => 'Director De Plaza', 'report_to' => 68, 'udn' => 'Queretaro', 'nivel' => 'Director C/PA', 'correo' => 'FranciscoRodriguez@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8093','departamento'=>'DG','password' => 'Fr8Zg3Ps8Vs'],
['username' => 'Emiliano Alvarado Alvarado', 'report_id' => '49', 'puesto' => 'Lider De Proyecto', 'report_to' => 46, 'udn' => 'Queretaro', 'nivel' => 'Coordinador C/PA', 'correo' => 'EmilianoAlvarado@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8086','departamento'=>'OPERACIONES','password' => 'Ic2Df3Hs4Mn'],
['username' => 'Shavtai Rodrigo Monter Bravo', 'report_id' => '50', 'puesto' => 'Gestor De Créditos', 'report_to' => 53, 'udn' => 'Queretaro', 'nivel' => 'Especialista S/PA', 'correo' => 'RodrigoMonter@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8105','departamento'=>'COMERCIAL','password' => 'Bm8Ih0Gd3Kh'],
['username' => 'Valeska Velasco Vargas', 'report_id' => '51', 'puesto' => 'Coordinador De Postventa', 'report_to' => 48, 'udn' => 'Queretaro', 'nivel' => 'Coordinador S/PA', 'correo' => 'valeskavelasco@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8141','departamento'=>'OPERACIONES','password' => 'Ot5Tu9Wp6Tu'],
['username' => 'Angelica Abarca Montes', 'report_id' => '52', 'puesto' => 'Analista Administrativo', 'report_to' => 45, 'udn' => 'Queretaro', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'angelicaabarca@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8145','departamento'=>'ADMON','password' => 'Wr5Co3Aq4Xy'],
['username' => 'Mizraim Salomon Gonzalez Hernandez', 'report_id' => '53', 'puesto' => 'Coordinador De Ventas', 'report_to' => 48, 'udn' => 'Queretaro', 'nivel' => 'Coordinador C/PA', 'correo' => 'SalomonGonzalez@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8404','departamento'=>'COMERCIAL','password' => 'Bp7Hi6Dv4Yj'],
['username' => 'Juan Antonio Alaniz Martinez', 'report_id' => '54', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 53, 'udn' => 'Queretaro', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'JuanAlaniz@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8288','departamento'=>'COMERCIAL','password' => 'Ou8Bb2Qt5Sl'],
['username' => 'Alan Alberto Soriano Salazar', 'report_id' => '55', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 53, 'udn' => 'Queretaro', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'alansoriano@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8290','departamento'=>'COMERCIAL','password' => 'Im2Sr2Cm5Ez'],
['username' => 'Roberto Escamilla Baños', 'report_id' => '56', 'puesto' => 'Supervisor De Urbanización', 'report_to' => 49, 'udn' => 'Queretaro', 'nivel' => 'Especialista S/PA', 'correo' => 'RobertoEscamilla@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8336','departamento'=>'OPERACIONES','password' => 'It7Kl1Lh7Lu'],
['username' => 'Francisco Amado Lopez Trujillo', 'report_id' => '57', 'puesto' => 'Supervisor De Urbanización', 'report_to' => 46, 'udn' => 'Queretaro', 'nivel' => 'Especialista S/PA', 'correo' => 'FranciscoLopez@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8343','departamento'=>'OPERACIONES','password' => 'It6Nd8Vw6Fm'],
['username' => 'Ivan Enrique Tavera Brambila', 'report_id' => '58', 'puesto' => 'Supervisor De Edificación', 'report_to' => 46, 'udn' => 'Queretaro', 'nivel' => 'Especialista S/PA', 'correo' => 'IvanTavera@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8374','departamento'=>'OPERACIONES','password' => 'Md5Hg9Cw0Av'],
['username' => 'Perfecto Fernando Perez Grimaldi', 'report_id' => '59', 'puesto' => 'Coordinador De Infraestructura', 'report_to' => 48, 'udn' => 'Queretaro', 'nivel' => 'Coordinador S/PA', 'correo' => 'PerfectoPerez@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8376','departamento'=>'OPERACIONES','password' => 'Xn6Wf8Xw8Yz'],
['username' => 'Nancy Martinez Espinosa', 'report_id' => '60', 'puesto' => 'Coordinador De Ventas', 'report_to' => 48, 'udn' => 'Queretaro', 'nivel' => 'Coordinador C/PA', 'correo' => 'NancyMartinez@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8405','departamento'=>'COMERCIAL','password' => 'Vi6Nx7Lp5Zq'],
['username' => 'Yahir Alejandro Coronado Pacheco', 'report_id' => '61', 'puesto' => 'Coordinador Corporativo De Postventa', 'report_to' => 70, 'udn' => 'SLP-Corpo', 'nivel' => 'Coordinador S/PA', 'correo' => 'AlejandroCoronado@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8007','departamento'=>'OPERACIONES','password' => 'Rt3Oz9Lk9Fy'],
['username' => 'Alfredo Ruiz Carrizalez', 'report_id' => '62', 'puesto' => 'Gerente De Construcción', 'report_to' => 70, 'udn' => 'SLP-Corpo', 'nivel' => 'Coordinador S/PA', 'correo' => 'AlfredoRuiz@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8063','departamento'=>'OPERACIONES','password' => 'Jw2Ym2Jr3Uh'],
['username' => 'Dulce Lucia Guevara Martinez', 'report_id' => '63', 'puesto' => 'Directora De Comercialización', 'report_to' => 68, 'udn' => 'SLP-Corpo', 'nivel' => 'Director C/PA', 'correo' => 'dulceguevara@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8101','departamento'=>'COMERCIAL','password' => 'Fb9Hq4Cq0Xn'],
['username' => 'Maria Petra Loera Arredondo', 'report_id' => '64', 'puesto' => 'Atención A Clientes', 'report_to' => 63, 'udn' => 'SLP-Corpo', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'marialoera@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8139','departamento'=>'COMERCIAL','password' => 'Ls3Fk6Zq8On'],
['username' => 'Marco Antonio Ruiz Garcia', 'report_id' => '65', 'puesto' => 'Gerente De Innovación Y Proyectos Especiales', 'report_to' => 63, 'udn' => 'SLP-Corpo', 'nivel' => 'Gerente C/PA', 'correo' => 'MarcoRuiz@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8180','departamento'=>'COMERCIAL','password' => 'Dz4Ju2Lm0Qj'],
['username' => 'Raul Alcauter Rueda', 'report_id' => '66', 'puesto' => 'Gerente De Proyectos', 'report_to' => 70, 'udn' => 'SLP-Corpo', 'nivel' => 'Gerente C/PA', 'correo' => 'RaulAlcauter@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8321','departamento'=>'OPERACIONES','password' => 'Lu8Vc2Du1Vf'],
['username' => 'Pedro Francisco Jimenez Leyva', 'report_id' => '67', 'puesto' => 'Auxiliar De Proyectos Especiales', 'report_to' => 65, 'udn' => 'SLP-Corpo', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'FranciscoJimenez@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'17006','departamento'=>'COMERCIAL','password' => 'Aj7Ob0Cu5Mf'],
['username' => 'Mauricio Allende Garcia', 'report_id' => '68', 'puesto' => 'Director General', 'report_to' => 1, 'udn' => 'SLP-Corpo', 'nivel' => 'Director C/PA', 'correo' => 'MauricioAllende@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8149','departamento'=>'DG','password' => 'Gl7Fu8Fc4Nt'],
['username' => 'Aristoteles Resendiz Flores', 'report_id' => '69', 'puesto' => 'Gerente De Planeación Operativa', 'report_to' => 70, 'udn' => 'SLP-Corpo', 'nivel' => 'Gerente C/PA', 'correo' => 'AristotelesResendiz@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8056','departamento'=>'OPERACIONES','password' => 'Xh2Pf2Eh4Yp'],
['username' => 'Alfonso Armeria Barreda', 'report_id' => '70', 'puesto' => 'Director De Construcción', 'report_to' => 68, 'udn' => 'SLP-Corpo', 'nivel' => 'Director C/PA', 'correo' => 'AlfonsoArmeria@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8194','departamento'=>'OPERACIONES','password' => 'Ih4Tr0Wz1Gl'],
['username' => 'Nicolas Cedillo Grimaldo', 'report_id' => '71', 'puesto' => 'Gerente de Costos y Presupuestos', 'report_to' => 70, 'udn' => 'SLP-Corpo', 'nivel' => 'Gerente S/PA', 'correo' => 'NicolasCedillo@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8394','departamento'=>'OPERACIONES','password' => 'Ae4Vj0Qz4Yx'],
['username' => 'Juan Aguirre Farrera', 'report_id' => '72', 'puesto' => 'Lider De Proyecto', 'report_to' => 74, 'udn' => 'Jalisco', 'nivel' => 'Coordinador C/PA', 'correo' => 'JuanAguirre@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8340','departamento'=>'OPERACIONES','password' => 'Bc8Oe4Fq8Ln'],
['username' => 'Emmanuel Carrillo Rodriguez', 'report_id' => '73', 'puesto' => 'Supervisor De Edificación', 'report_to' => 72, 'udn' => 'Jalisco', 'nivel' => 'Especialista S/PA', 'correo' => 'EmmanuelCarrillo@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8353','departamento'=>'OPERACIONES','password' => 'Qc8Qu8Zx8Jr'],
['username' => 'Francisco Javier Arenillas Cuetara', 'report_id' => '74', 'puesto' => 'Director De Plaza', 'report_to' => 68, 'udn' => 'Jalisco', 'nivel' => 'Director C/PA', 'correo' => 'JavierArenillas@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8355','departamento'=>'DG','password' => 'Zp6Ak3Ua8Ep'],
['username' => 'Luis Renato Leon Cuellar', 'report_id' => '75', 'puesto' => 'Supervisor De Edificación', 'report_to' => 72, 'udn' => 'Jalisco', 'nivel' => 'Especialista S/PA', 'correo' => 'LuisLeon@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8361','departamento'=>'OPERACIONES','password' => 'Sr5Qp0Fz9Ov'],
['username' => 'Grecia Susana Vargas Solis', 'report_id' => '76', 'puesto' => 'Coordinador Técnico-Administrativo', 'report_to' => 74, 'udn' => 'Jalisco', 'nivel' => 'Coordinador C/PA', 'correo' => 'GreciaVargas@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8365','departamento'=>'ADMON - OP','password' => 'Pk7Tm5Cs0Nx'],
['username' => 'Miguel Angel Flores Nicolas', 'report_id' => '77', 'puesto' => 'Auxiliar Técnico', 'report_to' => 76, 'udn' => 'Jalisco', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'MiguelFlores@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8375','departamento'=>'OPERACIONES','password' => 'Vl9Ao4No6Eo'],
['username' => 'Ivan Emmanuel Estrada Colunga', 'report_id' => '78', 'puesto' => 'Integrador De Expedientes', 'report_to' => 93, 'udn' => 'Jalisco', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'EmmanuelEstrada@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8409','departamento'=>'COMERCIAL','password' => 'Py8Mn2Pt7Xy'],
['username' => 'Selene Margarita Leon Portela', 'report_id' => '79', 'puesto' => 'Analista Administrativo', 'report_to' => 80, 'udn' => 'Cancún', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'SeleneLeon@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8341','departamento'=>'ADMON','password' => 'Hz9Av1Op6Uc'],
['username' => 'Victor Manuel Tinajero Ceballos', 'report_id' => '80', 'puesto' => 'Director De Plaza', 'report_to' => 68, 'udn' => 'Cancún', 'nivel' => 'Director C/PA', 'correo' => 'VictorTinajero@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8325','departamento'=>'DG','password' => 'Tb1Tn1Zw1Gk'],
['username' => 'Hector Martinez Zuñiga', 'report_id' => '81', 'puesto' => 'Supervisor De Obra', 'report_to' => 86, 'udn' => 'Aguascalientes', 'nivel' => 'Especialista S/PA', 'correo' => 'HectorMartinezZ@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8158','departamento'=>'OPERACIONES','password' => 'Wv4Bf9Nd5Ba'],
['username' => 'Sergio Ernesto Uribe Goytia', 'report_id' => '82', 'puesto' => 'Director De Plaza', 'report_to' => 68, 'udn' => 'Aguascalientes', 'nivel' => 'Director C/PA', 'correo' => 'SergioUribe@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8185','departamento'=>'DG','password' => '172P0yR#Hnx'],
['username' => 'Olga Veronica Delgado Palos', 'report_id' => '83', 'puesto' => 'Coordinador Administrativo', 'report_to' => 82, 'udn' => 'Aguascalientes', 'nivel' => 'Coordinador C/PA', 'correo' => 'VeronicaDelgado@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8193','departamento'=>'ADMON','password' => 'Jt6Pm2Ef4Gv'],
['username' => 'Dignangel Cristina Medina Rodriguez', 'report_id' => '84', 'puesto' => 'Analista Administrativo', 'report_to' => 83, 'udn' => 'Aguascalientes', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'DignangelMedina@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8274','departamento'=>'ADMON','password' => 'Eg7Ex5Mn8Ff'],
['username' => 'Oscar Leonardo Castañeda Diaz', 'report_id' => '85', 'puesto' => 'Coordinador De Ventas', 'report_to' => 82, 'udn' => 'Aguascalientes', 'nivel' => 'Coordinador S/PA', 'correo' => 'oscarcastaneda@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8403','departamento'=>'COMERCIAL','password' => 'Xf8Sb2Jq1Yj'],
['username' => 'Jorge Armando Gonzalez Sanchez', 'report_id' => '86', 'puesto' => 'Lider De Proyecto', 'report_to' => 82, 'udn' => 'Aguascalientes', 'nivel' => 'Coordinador C/PA', 'correo' => 'JorgeGonzalezS@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8395','departamento'=>'OPERACIONES','password' => 'Co1Mk9Vh0Ef'],
['username' => 'Claudia Gabriela Garcia Oviedo', 'report_id' => '87', 'puesto' => 'Coordinador De Ventas', 'report_to' => 28, 'udn' => 'San Miguel De Allende', 'nivel' => 'Coordinador C/PA', 'correo' => 'GabrielaGarcia@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'5','departamento'=>'COMERCIAL','password' => 'Sw1Dz9Uu5Ry'],
['username' => 'Luis Arturo Lopez Martinez', 'report_id' => '88', 'puesto' => 'Superintendente', 'report_to' => 28, 'udn' => 'Celaya', 'nivel' => 'Coordinador C/PA', 'correo' => 'ArturoLopez@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'4','departamento'=>'OPERACIONES','password' => 'Bb2Bg4Uh3Wx'],
['username' => 'Ulises Flores Rangel', 'report_id' => '89', 'puesto' => 'Jefe De Mercadotecnia', 'report_to' => 63, 'udn' => 'SLP-Corpo', 'nivel' => 'Especialista S/PA', 'correo' => 'UlisesFlores@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8411','departamento'=>'COMERCIAL','password' => 'Vb9Go1Ip5Zj'],
['username' => 'Nadja Alline Fajardo Vivar', 'report_id' => '90', 'puesto' => 'Becario De Desarrollo Organizacional', 'report_to' => 91, 'udn' => 'SLP-Corpo', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'auxiliar_do@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'15005','departamento'=>'DO','password' => 'Qq8Wj5Ib1Jt'],
['username' => 'Mayra Elva Quistian Blanco', 'report_id' => '91', 'puesto' => 'Coordinador De Desarrollo Organizacional', 'report_to' => 92, 'udn' => 'SLP-Corpo', 'nivel' => 'Coordinador C/PA', 'correo' => 'MayraQuistian@valoran.com.mx', 'TC' => '', 'PC' => '','num_nomina'=>'17001','departamento'=>'DO','password' => 'Ranman#23'],
['username' => 'Yary Magdalena Vargas De La Garza', 'report_id' => '92', 'puesto' => 'Directora DBH', 'report_to' => 68, 'udn' => 'SLP-Corpo', 'nivel' => 'Director C/PA', 'correo' => 'YaryVargas@paraserfeliz.mx', 'TC' => '', 'PC' => '','num_nomina'=>'17002','departamento'=>'DO','password' => 'Zq5Qu8Lm5Ay'],
['username' => 'Enriqueta Aracely Sanchez Santillan', 'report_id' => '93', 'puesto' => 'Coordinador De Ventas', 'report_to' => 74, 'udn' => 'Jalisco', 'nivel' => 'Coordinador C/PA', 'correo' => 'aracelysanchez@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14060','departamento'=>'COMERCIAL','password' => 'Bm0Cc8Cv6St'],
['username' => 'Carlos Francisco Cadena Del Angel', 'report_id' => '94', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 21, 'udn' => 'Aguascalientes', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'CarlosFCadena@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14003','departamento'=>'COMERCIAL','password' => 'Da2Tk0Kb1Tk'],
['username' => 'Alma Crystal Castillo Gamboa', 'report_id' => '95', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 21, 'udn' => 'Aguascalientes', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'AlmaCastilloG@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14067','departamento'=>'COMERCIAL','password' => 'Nh7Ti2Yz1Uj'],
['username' => 'Monica Jazmin Muñoz Garcia', 'report_id' => '96', 'puesto' => 'Coordinador Postventa', 'report_to' => 82, 'udn' => 'Aguascalientes', 'nivel' => 'Coordinador S/PA', 'correo' => 'MonicaMunoz@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8412','departamento'=>'OPERACIONES','password' => 'Ni1Cy7He0Kp'],
['username' => 'Jose Manuel Aburto Hernandez', 'report_id' => '97', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 53, 'udn' => 'Queretaro', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'joseaburto@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14025','departamento'=>'COMERCIAL','password' => 'Fx5Bk6Fo2Ra'],
['username' => 'Susana Marcela Berges Esquiliano', 'report_id' => '98', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 12, 'udn' => 'SLP-Plaza', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'MarcelaBerges@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14030','departamento'=>'COMERCIAL','password' => 'Nl4Dx7Ak6Tx'],
['username' => 'Esperanza Correa Vera', 'report_id' => '99', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 28, 'udn' => 'Celaya', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'EsparzaCorrea@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14053','departamento'=>'COMERCIAL','password' => 'Bq5Wm4Sf6Rk'],
['username' => 'Antonia Del Angel Diaz', 'report_id' => '100', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 16, 'udn' => 'Aguascalientes', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'Antoniadelangel@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14004','departamento'=>'COMERCIAL','password' => 'Zo6Vp1Rr1Qe'],
['username' => 'Francisco Elias Hernndez', 'report_id' => '101', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 16, 'udn' => 'Aguascalientes', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'FranciscoElias@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14055','departamento'=>'COMERCIAL','password' => 'Yl0Vu5Je2Py'],
['username' => 'Lesly Monserrat Galicia Juarez', 'report_id' => '102', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 21, 'udn' => 'Aguascalientes', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'LeslyGalicia@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14005','departamento'=>'COMERCIAL','password' => 'Vb1Ky2Fr0Rd'],
['username' => 'Maria Magdalena Galvan Valdez', 'report_id' => '103', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 28, 'udn' => 'Celaya', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'MariaGalvan@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14013','departamento'=>'COMERCIAL','password' => 'Nc0My9Gq1Bj'],
['username' => 'Karla Ruth Gonzalez Martinez', 'report_id' => '104', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 12, 'udn' => 'SLP-Plaza', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'KarlaGonzalez@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14033','departamento'=>'COMERCIAL','password' => 'Iz7Ss0Na7Uc'],
['username' => 'Maria De Los Angeles Gutierrez Arevalo', 'report_id' => '105', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 12, 'udn' => 'SLP-Plaza', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'AngelesGutierrez@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14034','departamento'=>'COMERCIAL','password' => 'It7Ys6Ka8Cs'],
['username' => 'Fernado Arturo Islas Salazar', 'report_id' => '106', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 16, 'udn' => 'Aguascalientes', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'FernandoIslas@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14063','departamento'=>'COMERCIAL','password' => 'Lt1Sv0Tc5Xi'],
['username' => 'Claudia Cristina Jimenez Rodriguez', 'report_id' => '107', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 93, 'udn' => 'Jalisco', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'ClaudiaJimenez@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14020','departamento'=>'COMERCIAL','password' => 'Qj6Ib5Uu9Yg'],
['username' => 'Martha Adriana Leon Alamilla', 'report_id' => '108', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 28, 'udn' => 'Celaya', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'AdrianaLeon@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14016','departamento'=>'COMERCIAL','password' => 'Xo1Hs4Dz6Yq'],
['username' => 'Norma Angelica Lopez Padilla', 'report_id' => '109', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 12, 'udn' => 'SLP-Plaza', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'NormaLopez@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14035','departamento'=>'COMERCIAL','password' => 'Zp0Pk0Qq3Uw'],
['username' => 'Juan Carlos Martinez Velasco', 'report_id' => '110', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 16, 'udn' => 'Aguascalientes', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'Juancarlosmartinez@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14056','departamento'=>'COMERCIAL','password' => 'Tl8Yq8Vq9Lu'],
['username' => 'Juana Del Carmen Mendoza Rodriguez', 'report_id' => '111', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 60, 'udn' => 'Queretaro', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'CarmenMedozaR@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14054','departamento'=>'COMERCIAL','password' => 'Uv1Tq1My8Kt'],
['username' => 'Gerardo Muñoz Alatorre', 'report_id' => '112', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 93, 'udn' => 'Jalisco', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'GerardoMunoz@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14021','departamento'=>'COMERCIAL','password' => 'Uh3Yq5Iq2Nh'],
['username' => 'Ana Rosa Palomo Govea', 'report_id' => '113', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 12, 'udn' => 'SLP-Plaza', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'AnaPalomo@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14039','departamento'=>'COMERCIAL','password' => 'Pg0Gk7Ow0Kp'],
['username' => 'Ma. Camelia Perez Flores', 'report_id' => '114', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 28, 'udn' => 'Celaya', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'CameliaPerez@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14052','departamento'=>'COMERCIAL','password' => 'Dg8It1Sf2Js'],
['username' => 'Carolina Salas Castillo', 'report_id' => '115', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 12, 'udn' => 'SLP-Plaza', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'CarolinaSalas@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14037','departamento'=>'COMERCIAL','password' => 'St6Jh0Bo7Sh'],
['username' => 'Esteban Manuel Salazar Ramirez', 'report_id' => '116', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 21, 'udn' => 'Aguascalientes', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'EstebanSalazar@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14007','departamento'=>'COMERCIAL','password' => 'Qn4Tn0Hg1Ii'],
['username' => 'Oscar Elpidio Sanchez Santillan', 'report_id' => '117', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 93, 'udn' => 'Jalisco', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'OscarSanchez@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14059','departamento'=>'COMERCIAL','password' => 'Xw0Pf6Cg3Bw'],
['username' => 'Flor Karina Vargas Gutierrez', 'report_id' => '118', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 85, 'udn' => 'Aguascalientes', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'KarinaVargas@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14062','departamento'=>'COMERCIAL','password' => 'Tc9Rr0Ia1Px'],
['username' => 'Jazmin Vazquez Nava', 'report_id' => '119', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 16, 'udn' => 'Aguascalientes', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'JazminVazquez@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14057','departamento'=>'COMERCIAL','password' => 'Nx6Tp6Mr1Iv'],
['username' => 'Maria Del Rocio Villa Villaseñor', 'report_id' => '120', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 53, 'udn' => 'Queretaro', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'RocioVilla@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14029','departamento'=>'COMERCIAL','password' => 'Id5Wp7Gr5Jn'],
['username' => 'Franchesca Garibaldi Luna', 'report_id' => '121', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 93, 'udn' => 'Jalisco', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'FranchescaGaribaldi@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14069','departamento'=>'COMERCIAL','password' => 'Rj2Ok2Sg4Om'],
['username' => 'Gisela Gabriela Gomez Gonzalez', 'report_id' => '122', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 60, 'udn' => 'Queretaro', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'GiselaGomez@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14072','departamento'=>'COMERCIAL','password' => 'Yi5Ma0Ve9Ql'],
['username' => 'Gabriela Aguirre Buitron', 'report_id' => '123', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 60, 'udn' => 'Queretaro', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'GabrielaAguirre@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14073','departamento'=>'COMERCIAL','password' => 'Pi9Zu2Mb7Oc'],
['username' => 'Dulce Edith Ortiz Martinez', 'report_id' => '124', 'puesto' => 'Auxiliar contable', 'report_to' => 34, 'udn' => 'SLP-Corpo', 'nivel' => 'Especialista S/PA', 'correo' => 'DulceOrtiz@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8413','departamento'=>'DAF','password' => 'Uw6Rp7Ou8Ae'],
['username' => 'Claudia Elvira Del Angel Perez', 'report_id' => '125', 'puesto' => 'Ejecutivo De Ventas', 'report_to' => 16, 'udn' => 'Aguascalientes', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'claudiadelangel@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14074','departamento'=>'COMERCIAL','password' => 'Sw7Nz0Gy8Uq'],
['username' => 'DIRECTOR SLP', 'report_id' => '126', 'puesto' => 'Director De Plaza', 'report_to' => 68, 'udn' => 'SLP-Plaza', 'nivel' => 'Director C/PA', 'correo' => '', 'TC' => '', 'PC' => '','num_nomina'=>'NULL','departamento'=>'DG','password' => 'Qc6Rk8Hr5Mx'],
['username' => 'Roberto Torres Pizano', 'report_id' => '127', 'puesto' => 'Coordinador de Ventas', 'report_to' => 28, 'udn' => 'Celaya', 'nivel' => 'Coordinador C/PA', 'correo' => 'RobertoTorres@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14078','departamento'=>'COMERCIAL','password' => 'Ks6Ao4Ut3Xx'],
['username' => 'Karla Manuela Garcia Juarez', 'report_id' => '128', 'puesto' => 'Gestor De Créditos', 'report_to' => 127, 'udn' => 'Celaya', 'nivel' => 'Especialista S/PA', 'correo' => 'karlagarcia@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14064','departamento'=>'COMERCIAL','password' => 'Gj6Mo4Mx4Gl'],
['username' => 'Evia Clara Vazquez Garcia', 'report_id' => '129', 'puesto' => 'Asesor Comercial', 'report_to' => 53, 'udn' => 'Queretaro', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'ElviaVazquez@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14077','departamento'=>'COMERCIAL','password' => 'El4Cr4Cm1My'],
['username' => 'Adriana Lorena Leon Nisino', 'report_id' => '130', 'puesto' => 'Asesor Comercial', 'report_to' => 53, 'udn' => 'Queretaro', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => 'LorenaLeon@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'14076','departamento'=>'COMERCIAL','password' => 'Vp0Xm1Du6Kl'],
['username' => 'Gabriela Franco Silva', 'report_id' => '131', 'puesto' => 'Directora De Desarrollo Comercial y Marketing', 'report_to' => 68, 'udn' => 'SLP-Corpo', 'nivel' => 'Director C/PA', 'correo' => 'GabrielaFranco@ranman.mx', 'TC' => '', 'PC' => '','num_nomina'=>'8414','departamento'=>'COMERCIAL','password' => 'Ij1Hj0Iz6Qa'],
['username' => 'EJEMPLO Director', 'report_id' => '132', 'puesto' => 'EJEMPLO Director', 'report_to' => 90, 'udn' => 'SLP-Corpo', 'nivel' => 'Director C/PA', 'correo' => '', 'TC' => '', 'PC' => '','num_nomina'=>'NULL','departamento'=>'DO','password' => 'Ejemplo23'],
['username' => 'EJEMPLO Gerente', 'report_id' => '133', 'puesto' => 'EJEMPLO Gerente', 'report_to' => 90, 'udn' => 'SLP-Corpo', 'nivel' => 'Gerente C/PA', 'correo' => '', 'TC' => '', 'PC' => '','num_nomina'=>'NULL','departamento'=>'DO','password' => 'Ejemplo23'],
['username' => 'EJEMPLO Coordinador', 'report_id' => '134', 'puesto' => 'EJEMPLO Coordinador', 'report_to' => 90, 'udn' => 'SLP-Corpo', 'nivel' => 'Coordinador C/PA', 'correo' => '', 'TC' => '', 'PC' => '','num_nomina'=>'NULL','departamento'=>'DO','password' => 'Ejemplo23'],
['username' => 'EJEMPLO Especialista', 'report_id' => '135', 'puesto' => 'EJEMPLO Especialista', 'report_to' => 90, 'udn' => 'SLP-Corpo', 'nivel' => 'Especialista S/PA', 'correo' => '', 'TC' => '', 'PC' => '','num_nomina'=>'NULL','departamento'=>'DO','password' => 'Ejemplo23'],
['username' => 'EJEMPLO Sp. Admin', 'report_id' => '136', 'puesto' => 'EJEMPLO Sp. Admin', 'report_to' => 90, 'udn' => 'SLP-Corpo', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => '', 'TC' => '', 'PC' => '','num_nomina'=>'NULL','departamento'=>'DO','password' => 'Ejemplo23'],
['username' => 'EJEMPLO 1.1 Director', 'report_id' => '137', 'puesto' => 'EJEMPLO 1.1 Director', 'report_to' => 91, 'udn' => 'SLP-Corpo', 'nivel' => 'Director C/PA', 'correo' => '', 'TC' => '', 'PC' => '','num_nomina'=>'NULL','departamento'=>'DO','password' => 'Ejemplo2324'],
['username' => 'EJEMPLO 1.1 Gerente', 'report_id' => '138', 'puesto' => 'EJEMPLO 1.1 Gerente', 'report_to' => 91, 'udn' => 'SLP-Corpo', 'nivel' => 'Gerente C/PA', 'correo' => '', 'TC' => '', 'PC' => '','num_nomina'=>'NULL','departamento'=>'DO','password' => 'Ejemplo2324'],
['username' => 'EJEMPLO 1.1 Coordinador', 'report_id' => '139', 'puesto' => 'EJEMPLO 1.1 Coordinador', 'report_to' => 91, 'udn' => 'SLP-Corpo', 'nivel' => 'Coordinador C/PA', 'correo' => '', 'TC' => '', 'PC' => '','num_nomina'=>'NULL','departamento'=>'DO','password' => 'Ejemplo2324'],
['username' => 'EJEMPLO 1.1 Especialista', 'report_id' => '140', 'puesto' => 'EJEMPLO 1.1 Especialista', 'report_to' => 91, 'udn' => 'SLP-Corpo', 'nivel' => 'Especialista S/PA', 'correo' => '', 'TC' => '', 'PC' => '','num_nomina'=>'NULL','departamento'=>'DO','password' => 'Ejemplo2324'],
['username' => 'EJEMPLO 1.1 Sp. Admin', 'report_id' => '141', 'puesto' => 'EJEMPLO 1.1 Sp. Admin', 'report_to' => 91, 'udn' => 'SLP-Corpo', 'nivel' => 'Soporte Administrativo S/PA', 'correo' => '', 'TC' => '', 'PC' => '','num_nomina'=>'NULL','departamento'=>'DO','password' => 'Ejemplo2324'],

        ];
        foreach ($data as $d) {
            
            $job = Job::firstOrCreate([
                'name' => $d['puesto']                
            ]);
            $level = Level::firstOrCreate([
                'name' => $d['nivel']
            ]);
            $udn = Udn::firstOrCreate([
                'name' => $d['udn']
            ]);      
            $departamento = Departamento::firstOrCreate([
                'name' => $d['departamento']
            ]);       
            $user = User::create([
                'name' => $d["username"],
                'email' => $d['correo'] ?? (str_replace(" ", "", $d["username"]) . "@ranman.mx"),
                'job_id' => $job->id,
                'report_to' => $d['report_to'],
                'level_id' => $level->id,
                'departamento_id'=>$departamento->id,
                'udn_id' => $udn->id,                
                'report_id' => $d['report_id'],          
                'puesto_critico' => $d['PC'] == 'X',
                'talento_clave' => $d['TC'] == 'X',   
                'password' => bcrypt('R4nm4n#2023'),          
            ]);


        }
    }
}
