<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Job;
use App\Models\Profile;
use App\Models\Udn;
use App\Models\Level;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // $this->disableForeign();
        $this->import();
        // $this->enableForeign();
    }


    protected function disableForeign()
    {
        Schema::table('profiles', function (Blueprint $table) {
            $table->dropForeign('profiles_report_to_foreign');
        });
    }

    protected function enableForeign()
    {
        Schema::table('profiles', function (Blueprint $table) {
            $table->foreign('report_to')->references('id')->on('profiles');
        });
    }


    protected function import()
    {
        $data = [
            ['username' => 'Vicente Rangel Mancilla', 'report_id' => '1', 'puesto' => 'Presidente de Consejo', 'report_to' => null, 'udn' => 'Corporativo', 'nivel' => 'N/A', 'correo' => 'vicente.rangel@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Sergio Godinez Giblas', 'report_id' => '2', 'puesto' => 'Director General', 'report_to' => '1', 'udn' => 'Corporativo', 'nivel' => 'Dirección', 'correo' => 'sergiogodinez@valoran.com.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Jose Luis Contreras Perez', 'report_id' => '3', 'puesto' => 'Director Estratégico Corporativo', 'report_to' => '1', 'udn' => 'Corporativo', 'nivel' => 'Dirección', 'correo' => 'jl@valoran.com.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Milton Jesus Martinez Melgarejo', 'report_id' => '4', 'puesto' => 'Director de Desarrollo de Negocios', 'report_to' => '2', 'udn' => 'Corporativo', 'nivel' => 'Dirección', 'correo' => 'milton.martinez@valoran.com.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Manuel Gonzalez Davila', 'report_id' => '5', 'puesto' => 'Director de Administración y Finanzas ', 'report_to' => '2', 'udn' => 'Corporativo', 'nivel' => 'Dirección', 'correo' => 'manuelgonzalez@valoran.com.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Yary Magdalena Vargas De La Garza', 'report_id' => '6', 'puesto' => 'Directora de Desarrollo y Bienestar Humano', 'report_to' => '2', 'udn' => 'Corporativo', 'nivel' => 'Dirección', 'correo' => 'YaryVargas@valoran.com.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Celeste Rebora Mier', 'report_id' => '7', 'puesto' => 'Directora de Relaciones Institucionales', 'report_to' => '3', 'udn' => 'Corporativo', 'nivel' => 'Dirección', 'correo' => 'CR@valoran.com.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Gabriela Motilla Chávez', 'report_id' => '8', 'puesto' => 'Gerente Jurídico', 'report_to' => '2', 'udn' => 'Corporativo', 'nivel' => 'Gerencia', 'correo' => 'GabrielaMotilla@valoran.com.mx', 'TC' => '', 'PC' => 'X'],
            ['username' => 'Diana Patricia Andrade Macias', 'report_id' => '9', 'puesto' => 'Asistente de Dirección', 'report_to' => '3', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'DianaAndrade@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Iliana Marquez Ortiz', 'report_id' => '10', 'puesto' => 'Recepción y Asistente de Dirección', 'report_to' => '9', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'IlianaMarquez@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Jose Manuel De Avila Rojas', 'report_id' => '11', 'puesto' => 'Especialista en Comunicación Institucional', 'report_to' => '3', 'udn' => 'Corporativo', 'nivel' => 'Especialista ', 'correo' => 'JoseDeAvila@valoran.com.mx', 'TC' => 'X', 'PC' => ''],
            ['username' => 'Diego Eduardo García Moreno De Rivera', 'report_id' => '12', 'puesto' => 'Gerente de Desarrollo de Negocios', 'report_to' => '4', 'udn' => 'Corporativo', 'nivel' => 'Gerencia', 'correo' => 'diegogarciamoreno@valoran.com.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Miguel Angel Almanza Ríos', 'report_id' => '13', 'puesto' => 'Analista de Desarrollo de Negocios', 'report_to' => '12', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'MiguelAlmanza@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Jaqueline Guadalupe Lopez Cervantes', 'report_id' => '14', 'puesto' => 'Analista de Desarrollo de Negocios', 'report_to' => '12', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'JaquelineLopez@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Daniel Armando Flores Badillo', 'report_id' => '15', 'puesto' => 'Coordinador de Planeación Financiera y  Estratégica', 'report_to' => '5', 'udn' => 'Corporativo', 'nivel' => 'Coordinación', 'correo' => 'Danielflores@valoran.com.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Daniela De Alba Olivo ', 'report_id' => '16', 'puesto' => 'Especialista Financiero', 'report_to' => '15', 'udn' => 'Corporativo', 'nivel' => 'Especialista ', 'correo' => 'DanieladeAlba@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Sebastian Rodriguez', 'report_id' => '17', 'puesto' => 'Analista Sr. Financiero', 'report_to' => '15', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'sebastianrodriguez@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Jose Arturo Zapata Moreno', 'report_id' => '18', 'puesto' => 'Gerente de Desarrollo de Negocios', 'report_to' => '4', 'udn' => 'Corporativo', 'nivel' => 'Gerencia', 'correo' => 'JoseArturoZapata@valoran.com.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Gabriel Alejandro Carranza Abaid', 'report_id' => '19', 'puesto' => 'Especialista Financiero', 'report_to' => '15', 'udn' => 'Corporativo', 'nivel' => 'Especialista ', 'correo' => 'GabrielCarranza@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Mayra Maidi Camacho Santos', 'report_id' => '20', 'puesto' => 'Coordinador de Nóminas', 'report_to' => '5', 'udn' => 'Corporativo', 'nivel' => 'Coordinación', 'correo' => 'mayracamacho@valoran.com.mx', 'TC' => '', 'PC' => 'X'],
            ['username' => 'Martha Alicia Quistian Ramirez', 'report_id' => '21', 'puesto' => 'Analista Sr. de Nóminas', 'report_to' => '20', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'MarthaQuistianR@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Oscar Antonio Saucedo Carreón', 'report_id' => '22', 'puesto' => 'Analista Jr. de Nóminas', 'report_to' => '20', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'OscarSaucedo@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Liliana Del Carmen Ramirez González', 'report_id' => '23', 'puesto' => 'Coordinador de Capital Humano', 'report_to' => '5', 'udn' => 'Corporativo', 'nivel' => 'Coordinación', 'correo' => 'LilianaRamirez@valoran.com.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Karina Elizabeth Balderas González', 'report_id' => '24', 'puesto' => 'Analista Jr. de Atracción de Talento', 'report_to' => '23', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'KarinaBalderas@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Naomi Itzel Arias Martinez', 'report_id' => '26', 'puesto' => 'Analista Jr. de Capital Humano', 'report_to' => '23', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'NaomiArias@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Alicia Maria Vázquez Gómez', 'report_id' => '27', 'puesto' => 'Gerente de Administración y Contraloría', 'report_to' => '5', 'udn' => 'Corporativo', 'nivel' => 'Gerencia', 'correo' => 'Alicia.Vazquez@valoran.com.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Victor Manuel Saucedo Ramirez', 'report_id' => '28', 'puesto' => 'Coordinador de Contraloría', 'report_to' => '27', 'udn' => 'Corporativo', 'nivel' => 'Coordinación', 'correo' => 'VictorSaucedo@valoran.com.mx', 'TC' => 'X', 'PC' => ''],
            ['username' => 'Luz Adriana Moreno Alanis', 'report_id' => '29', 'puesto' => 'Coordinador de Mantenimiento', 'report_to' => '28', 'udn' => 'Corporativo', 'nivel' => 'Coordinación', 'correo' => 'Adrianamoreno@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Felipe Guillermo Alvarado Silva ', 'report_id' => '31', 'puesto' => 'Analista de Contraloría', 'report_to' => '28', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'FelipeAlvarado@valoran.com.mx', 'TC' => 'X', 'PC' => ''],
            ['username' => 'Joaquín Serrato Frausto', 'report_id' => '32', 'puesto' => 'Especialista Fiscal ', 'report_to' => '27', 'udn' => 'Corporativo', 'nivel' => 'Especialista ', 'correo' => 'JoaquinSerrato@valoran.com.mx', 'TC' => '', 'PC' => 'X'],
            ['username' => 'Jessica Berenice Palacios Gomez ', 'report_id' => '33', 'puesto' => 'Contador General ', 'report_to' => '27', 'udn' => 'Corporativo', 'nivel' => 'Coordinación', 'correo' => 'jessicapalacios@valoran.com.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Andrea Susana Perez Rodriguez', 'report_id' => '34', 'puesto' => 'Contador Sr.', 'report_to' => '33', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'AndreaPerez@valoran.com.mx', 'TC' => 'X', 'PC' => ''],
            ['username' => 'Evelin Aurora Morales Estrada', 'report_id' => '35', 'puesto' => 'Auxiliar Administrativo Contable', 'report_to' => '36', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'EvelynMorales@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Arely Jacqueline Diaz Gomez', 'report_id' => '36', 'puesto' => 'Contador Jr.', 'report_to' => '33', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'ArelyDiaz@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Daniela Aránzazu Agundis Zuñiga', 'report_id' => '37', 'puesto' => 'Contador Jr.', 'report_to' => '33', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'DanielaZuniga@valoran.com.mx', 'TC' => 'X', 'PC' => ''],
            ['username' => 'Cecilia Edith Mendoza Salazar', 'report_id' => '38', 'puesto' => 'Auxiliar Administrativo Contable', 'report_to' => '34', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'CeciliaMendoza@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Sylvia Del Rocío Resendiz Gallardo', 'report_id' => '39', 'puesto' => 'Gerente de Contabilidad ', 'report_to' => '27', 'udn' => 'Corporativo', 'nivel' => 'Gerencia', 'correo' => 'SylviaResendiz@valoran.com.mx', 'TC' => '', 'PC' => 'X'],
            ['username' => 'Rufina Noyola Rodriguez', 'report_id' => '40', 'puesto' => 'Contador General ', 'report_to' => '39', 'udn' => 'Corporativo', 'nivel' => 'Coordinación', 'correo' => 'RufinaNoyolaR@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Oscar Ortiz Urbina', 'report_id' => '41', 'puesto' => 'Gerente de TI', 'report_to' => '5', 'udn' => 'Corporativo', 'nivel' => 'Gerencia', 'correo' => 'OscarOrtiz@valoran.com.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Simon Francisco Banda Avila', 'report_id' => '42', 'puesto' => 'Coordinador de Aplicaciones ', 'report_to' => '41', 'udn' => 'Corporativo', 'nivel' => 'Coordinación', 'correo' => 'simonbanda@valoran.com.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Angel Daniel Zarate Hernandez', 'report_id' => '43', 'puesto' => 'Analista Sr. de Sistemas de Información', 'report_to' => '42', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'AngelZarate@valoran.com.mx ', 'TC' => '', 'PC' => ''],
            ['username' => 'Maria De Jesus Reyna Martinez', 'report_id' => '44', 'puesto' => 'Consultor Funcional', 'report_to' => '41', 'udn' => 'Corporativo', 'nivel' => 'Coordinación', 'correo' => 'MariaReyna@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Josué Rodriguez Muñoz', 'report_id' => '45', 'puesto' => 'Consultor de Implementación', 'report_to' => '44', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'JosueRodriguez@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Silvia Rangel Maldonado', 'report_id' => '46', 'puesto' => 'Ingeniero de Soporte ', 'report_to' => '158', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'SilviaRangel@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Roberto Davila Hernandez', 'report_id' => '47', 'puesto' => 'Especialista en Infraestructura y Ciberseguridad', 'report_to' => '41', 'udn' => 'Corporativo', 'nivel' => 'Especialista ', 'correo' => 'robertodavila@valoran.com.mx', 'TC' => '', 'PC' => 'X'],
            ['username' => 'Vacante', 'report_id' => '48', 'puesto' => 'Coordinador de Desarrollo Organizacional', 'report_to' => '6', 'udn' => 'Corporativo', 'nivel' => 'Coordinación', 'correo' => '', 'TC' => '', 'PC' => 'X'],
            ['username' => 'Maria Jose Aranda Gonzalez', 'report_id' => '49', 'puesto' => 'Coordinador de Bienestar', 'report_to' => '6', 'udn' => 'Corporativo', 'nivel' => 'Coordinación', 'correo' => 'Mariajosearanda@paraserfelix.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Mariana Hernandez Padilla', 'report_id' => '50', 'puesto' => 'Gestora de Bienestar y Eventos', 'report_to' => '49', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'MarianaHernandez@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Tania Del Carmen Lopez Torres', 'report_id' => '51', 'puesto' => 'Gestora de Bienestar y Administración', 'report_to' => '49', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'TaniaLopez@paraserfeliz.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Isidro Cardoso Cisneros', 'report_id' => '52', 'puesto' => 'Gerente de Estructuración Financiera y Compliance ', 'report_to' => '4', 'udn' => 'Corporativo', 'nivel' => 'Gerencia', 'correo' => 'IsidroCardoso@valoran.com.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Monserrat Mireles', 'report_id' => '53', 'puesto' => 'Auxiliar de Reclutamiento', 'report_to' => '23', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'MonserratMireles@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Stephanie Zamudio', 'report_id' => '54', 'puesto' => 'Analista Jr. De Nomina ', 'report_to' => '20', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'StephanieZamudio@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Socorro Aguilera Ramos', 'report_id' => '69', 'puesto' => 'Analista Jr. de Sistemas de Información', 'report_to' => '42', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'coco@valledeloscedros.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Vacante', 'report_id' => '158', 'puesto' => 'Coordinador de Soporte Tecnico', 'report_to' => '41', 'udn' => 'Corporativo', 'nivel' => 'Coordinación', 'correo' => '', 'TC' => '', 'PC' => ''],
            ['username' => 'Natalia Trujillo Martinez', 'report_id' => '55', 'puesto' => 'Coordinador Administrativo', 'report_to' => '155', 'udn' => 'Reserva Territorial', 'nivel' => 'Especialista ', 'correo' => 'NataliaTrujillo@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Leticia López Alvarez', 'report_id' => '57', 'puesto' => 'Coordinador de Gestión Institucional ', 'report_to' => '155', 'udn' => 'Reserva Territorial', 'nivel' => 'Especialista ', 'correo' => 'LeticiaLopez@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Alejandro Oropeza Jimenez', 'report_id' => '58', 'puesto' => 'Gerente de Negociación', 'report_to' => '155', 'udn' => 'Reserva Territorial', 'nivel' => 'Gerencia', 'correo' => 'AlejandoOropeza@valoran.com.mx', 'TC' => '', 'PC' => 'X'],
            ['username' => 'Bernardo Aguilar Noyola ', 'report_id' => '59', 'puesto' => 'Coordinador de Proyectos', 'report_to' => '58', 'udn' => 'Reserva Territorial', 'nivel' => 'Soporte Administrativo', 'correo' => 'BernardoAguilar@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Angel Lardizabal Villanueva', 'report_id' => '60', 'puesto' => 'Cartografía', 'report_to' => '58', 'udn' => 'Reserva Territorial', 'nivel' => 'Soporte Administrativo', 'correo' => 'AngelLardizabal@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Sonia Mosquera Fernandez', 'report_id' => '61', 'puesto' => 'Gerente Ambiental', 'report_to' => '155', 'udn' => 'Reserva Territorial', 'nivel' => 'Gerencia', 'correo' => 'soniamosquera@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Gisela Guadalupe Silva Hernandez', 'report_id' => '62', 'puesto' => 'Gerente de Regularización', 'report_to' => '155', 'udn' => 'Reserva Territorial', 'nivel' => 'Gerencia', 'correo' => 'giselasilva@valoran.com.mx', 'TC' => '', 'PC' => 'X'],
            ['username' => 'Alejandra Gonzalez Cavazos', 'report_id' => '63', 'puesto' => 'Encargado de Archivo', 'report_to' => '62', 'udn' => 'Reserva Territorial', 'nivel' => 'Soporte Administrativo', 'correo' => 'AlejandraGonzalez@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Nelida Yazmin Barbosa Ramirez', 'report_id' => '64', 'puesto' => 'Analista Jurídico ', 'report_to' => '155', 'udn' => 'Reserva Territorial', 'nivel' => 'Soporte Administrativo', 'correo' => 'NelidaBarbosa@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Gabriela Balbontín', 'report_id' => '65', 'puesto' => 'Ejecutivo de Proyectos ', 'report_to' => '62', 'udn' => 'Reserva Territorial', 'nivel' => 'Soporte Administrativo', 'correo' => 'GabrielaBalbontin@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'David Eduardo Zavala Arciaga', 'report_id' => '155', 'puesto' => 'Director de Reserva Territorial', 'report_to' => '3', 'udn' => 'Reserva Territorial', 'nivel' => 'Dirección', 'correo' => 'DavidZavala@valoran.com.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Rafael De Leon Bach', 'report_id' => '66', 'puesto' => 'Director de Valle de los Cedros', 'report_to' => '2', 'udn' => 'Valle de los cedros', 'nivel' => 'Dirección', 'correo' => 'RafaelDeLeon@valledeloscedros.com.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Liliana Guadalupe Rico Martínez ', 'report_id' => '67', 'puesto' => 'Auxiliar Contable', 'report_to' => '40', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'LilianaRico@valledeloscedros.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'María Del Carmen Quintero Ramirez', 'report_id' => '68', 'puesto' => 'Auxiliar Contable', 'report_to' => '40', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'MariaQuintero@valledeloscedros.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Annel Castillo Arredondo', 'report_id' => '70', 'puesto' => 'Ingeniero de Soporte ', 'report_to' => '158', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'AnnelCastillo@valledeloscedros.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Daniela Barajas Landeros', 'report_id' => '71', 'puesto' => 'Coordinador de Servicio al Cliente ', 'report_to' => '66', 'udn' => 'Valle de los cedros', 'nivel' => 'Coordinación', 'correo' => 'DanielaBarajas@valledeloscedros.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Dianne Andrea Cerda Ortiz', 'report_id' => '72', 'puesto' => 'Auxiliar de Diseño', 'report_to' => '71', 'udn' => 'Valle de los cedros', 'nivel' => 'Soporte Administrativo', 'correo' => 'AndreaCerda@valledeloscedros.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Mauricio Alvarado Gallegos', 'report_id' => '73', 'puesto' => 'Gerente Administrativo ', 'report_to' => '66', 'udn' => 'Valle de los cedros', 'nivel' => 'Gerencia', 'correo' => 'MauricioAlvarado@valledeloscedros.com.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Rocio Arvizu Acosta', 'report_id' => '74', 'puesto' => 'Contador General ', 'report_to' => '73', 'udn' => 'Valle de los cedros', 'nivel' => 'Coordinación', 'correo' => 'RocioArvizu@valledeloscedros.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Diana Laura Estrada Mata', 'report_id' => '75', 'puesto' => 'Auxiliar Administrativo', 'report_to' => '74', 'udn' => 'Valle de los cedros', 'nivel' => 'Soporte Administrativo', 'correo' => 'DianaEstrada@valledeloscedros.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Juana Selene Huerta Carranco', 'report_id' => '76', 'puesto' => 'Analista Jr. de Compras', 'report_to' => '73', 'udn' => 'Valle de los cedros', 'nivel' => 'Soporte Administrativo', 'correo' => 'SeleneHuerta@valledeloscedros.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Ramon Jaaziel Zuñiga Castillo', 'report_id' => '77', 'puesto' => 'Encargado de Archivo', 'report_to' => '73', 'udn' => 'Valle de los cedros', 'nivel' => 'Soporte Administrativo', 'correo' => 'RamonZuniga@valledeloscedros.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Carlos Guadalupe Rodriguez Rodriguez', 'report_id' => '78', 'puesto' => 'Auxiliar de Archivo', 'report_to' => '77', 'udn' => 'Valle de los cedros', 'nivel' => 'Soporte Administrativo', 'correo' => 'CarlosRodriguez@valledeloscedros.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Monica Castillo Garcia', 'report_id' => '79', 'puesto' => 'Coordinador de Cobranza', 'report_to' => '73', 'udn' => 'Valle de los cedros', 'nivel' => 'Coordinación', 'correo' => 'MonicaCastillo@valledeloscedros.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Maria Andrea Ramos Ramirez', 'report_id' => '80', 'puesto' => 'Auxiliar de Cobranza', 'report_to' => '79', 'udn' => 'Valle de los cedros', 'nivel' => 'Soporte Administrativo', 'correo' => 'AndreaRamos@valledeloscedros.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Sidronio Milan Perez', 'report_id' => '81', 'puesto' => 'Auxiliar de Cobranza', 'report_to' => '79', 'udn' => 'Valle de los cedros', 'nivel' => 'Soporte Administrativo', 'correo' => 'SidronioMilan@valledeloscedros.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Sonia Lizeth Lopez Llanas', 'report_id' => '82', 'puesto' => 'Auxiliar de Cobranza', 'report_to' => '79', 'udn' => 'Valle de los cedros', 'nivel' => 'Soporte Administrativo', 'correo' => 'SoniaLopez@valledeloscedros.com.mx', 'TC' => 'X', 'PC' => ''],
            ['username' => 'Maira Nereida Perez Lopez', 'report_id' => '83', 'puesto' => 'Coordinador de Cuentas por Cobrar ', 'report_to' => '79', 'udn' => 'Valle de los cedros', 'nivel' => 'Coordinación', 'correo' => 'MairaPerez@valledeloscedros.com.mx', 'TC' => 'X', 'PC' => ''],
            ['username' => 'Felipe Carlos Garcia Tellez', 'report_id' => '84', 'puesto' => 'Gerente de Operaciones', 'report_to' => '66', 'udn' => 'Valle de los cedros', 'nivel' => 'Gerencia', 'correo' => 'FelipeGarcia@valledeloscedros.com.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Santiago Estrada Huerta', 'report_id' => '85', 'puesto' => 'Coordinador de Operaciones', 'report_to' => '84', 'udn' => 'Valle de los cedros', 'nivel' => 'Coordinación', 'correo' => 'SantiagoEstrada@valledeloscedros.com.mx', 'TC' => 'X', 'PC' => ''],
            ['username' => 'Rosa Elena Suchil Ortiz', 'report_id' => '86', 'puesto' => 'Coordinador de Operaciones y Atención al Cliente ', 'report_to' => '84', 'udn' => 'Valle de los cedros', 'nivel' => 'Coordinación', 'correo' => 'RosaSuchil@valledeloscedros.com.mx', 'TC' => 'X', 'PC' => ''],
            ['username' => 'Maria Gabriela Alonso Gonzalez  ', 'report_id' => '87', 'puesto' => 'Auxiliar de Operaciones', 'report_to' => '86', 'udn' => 'Valle de los cedros', 'nivel' => 'Soporte Administrativo', 'correo' => 'GabrielaAlonso@valledeloscedros.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Francisco Jose Hernández Fragoso', 'report_id' => '88', 'puesto' => 'Gerente Comercial', 'report_to' => '66', 'udn' => 'Valle de los cedros', 'nivel' => 'Gerencia', 'correo' => 'FranciscoHernandez@valledeloscedros.com.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Veronica Montante Miranda', 'report_id' => '89', 'puesto' => 'Auxiliar de Comercialización', 'report_to' => '88', 'udn' => 'Valle de los cedros', 'nivel' => 'Soporte Administrativo', 'correo' => 'VeronicaMontante@valledeloscedros.com.mx', 'TC' => 'X', 'PC' => ''],
            ['username' => 'Javier Dionicio Cerrillo Mayorga', 'report_id' => '90', 'puesto' => 'Coordinador Comercial', 'report_to' => '88', 'udn' => 'Valle de los cedros', 'nivel' => 'Coordinación', 'correo' => 'javiercerrillo@valledeloscedros.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Michele Porrino Perrasi', 'report_id' => '91', 'puesto' => 'Director de W.T.C.', 'report_to' => '2', 'udn' => 'W.T.C', 'nivel' => 'Dirección', 'correo' => 'MichelePorrino@wtcindustrial.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Claudia Denny Zaragoza Castillo', 'report_id' => '92', 'puesto' => 'Contador Jr.', 'report_to' => '39', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'ClaudiaZaragoza@wtcindustrial.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Aaron Israel Garcia Contreras', 'report_id' => '93', 'puesto' => 'Contador Jr.', 'report_to' => '39', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'AaronGarcia@wtcindustrial.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Mariela Alejandra Dominguez Perez', 'report_id' => '94', 'puesto' => 'Auxiliar Contable', 'report_to' => '39', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'MarielaDominguez@wtcindustrial.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Gustavo Garcia Soria Ortiz', 'report_id' => '95', 'puesto' => 'Ingeniero de Soporte ', 'report_to' => '158', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'GustavoGarcia@wtcindustrial.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Guadalupe Álvarez Martínez', 'report_id' => '96', 'puesto' => 'Coordinador de RFE y Atención al cliente ', 'report_to' => '91', 'udn' => 'W.T.C', 'nivel' => 'Gerencia', 'correo' => 'guadalupe.alvarez@wtcindustrial.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Veronica Lugo Balderas', 'report_id' => '97', 'puesto' => 'Supervisor de Seguridad', 'report_to' => '96', 'udn' => 'W.T.C', 'nivel' => 'Coordinación', 'correo' => 'recintofiscalizado@wtc.industrial.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Mario Guillermo Baez Camargo Castellanos', 'report_id' => '98', 'puesto' => 'Gerente de Desarrollo de Proyectos', 'report_to' => '91', 'udn' => 'W.T.C', 'nivel' => 'Gerencia', 'correo' => 'mariobaez@wtcindustrial.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Carlos Rodrigo López Arias', 'report_id' => '99', 'puesto' => 'Gerente de Proyectos', 'report_to' => '91', 'udn' => 'W.T.C', 'nivel' => 'Gerencia', 'correo' => 'RodrigoLopez@wtcindustrial.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Juan José Sánchez López', 'report_id' => '100', 'puesto' => 'Coordinador de Infraestructura', 'report_to' => '99', 'udn' => 'W.T.C', 'nivel' => 'Coordinación', 'correo' => 'juanjsanchez@wtcindustrial.mx', 'TC' => '', 'PC' => 'X'],
            ['username' => 'Sabrina Soberon Azuara', 'report_id' => '101', 'puesto' => 'Coordinador de Proyectos', 'report_to' => '99', 'udn' => 'W.T.C', 'nivel' => 'Coordinación', 'correo' => 'sabrinasoberon@wtcindustrial.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Luz Edith Narváez Carrizalez', 'report_id' => '102', 'puesto' => 'Analista Jr. de Proyectos', 'report_to' => '100', 'udn' => 'W.T.C', 'nivel' => 'Soporte Administrativo', 'correo' => 'edithnarvaez@wtcindustrial.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Janeth E. González Infante ', 'report_id' => '103', 'puesto' => 'Analista Jr. de Proyectos', 'report_to' => '101', 'udn' => 'W.T.C', 'nivel' => 'Soporte Administrativo', 'correo' => 'janetgonzalez@wtcindustrial.mx', 'TC' => 'X', 'PC' => ''],
            ['username' => 'Gaston Vivas Govea', 'report_id' => '104', 'puesto' => 'Gerente Administrativo ', 'report_to' => '91', 'udn' => 'W.T.C', 'nivel' => 'Gerencia', 'correo' => 'gastonvivas@wtcindustrial.mx', 'TC' => 'X', 'PC' => ''],
            ['username' => 'Rosa Maria Flores Murillo', 'report_id' => '105', 'puesto' => 'Contador General ', 'report_to' => '104', 'udn' => 'W.T.C', 'nivel' => 'Coordinación', 'correo' => 'RosaFlores@wtcindustrial.mx', 'TC' => 'X', 'PC' => ''],
            ['username' => 'Sergio Francisco Gámez Gomez', 'report_id' => '106', 'puesto' => 'Contador Sr.', 'report_to' => '105', 'udn' => 'W.T.C', 'nivel' => 'Soporte Administrativo', 'correo' => 'sergiogamez@wtcindustrial.mx', 'TC' => 'X', 'PC' => ''],
            ['username' => 'Cynthia Judith Salas Rivera', 'report_id' => '107', 'puesto' => 'Auxiliar Administrativo', 'report_to' => '105', 'udn' => 'W.T.C', 'nivel' => 'Soporte Administrativo', 'correo' => 'Judith.alvarez@parquelogistico.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Adriana Medina Gutierrez', 'report_id' => '108', 'puesto' => 'Analista Jr. de Administración', 'report_to' => '104', 'udn' => 'W.T.C', 'nivel' => 'Soporte Administrativo', 'correo' => 'AdrianaMedina@wtcindustrial.mx', 'TC' => 'X', 'PC' => ''],
            ['username' => 'Karla Wendy Jiménez Cabrera', 'report_id' => '109', 'puesto' => 'Tesorera', 'report_to' => '104', 'udn' => 'W.T.C', 'nivel' => 'Soporte Administrativo', 'correo' => 'Karlajimenez@wtcindustrial.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Fermín Rodriguez Sosa', 'report_id' => '110', 'puesto' => 'Gerente Comercial', 'report_to' => '91', 'udn' => 'W.T.C', 'nivel' => 'Gerencia', 'correo' => 'FermínRodriguez@wtcindustrial.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Jorge Eduardo Muñoz Solis', 'report_id' => '111', 'puesto' => 'Gerente de Operaciones', 'report_to' => '91', 'udn' => 'W.T.C', 'nivel' => 'Gerencia', 'correo' => 'JorgeMunoz@wtcindustrial.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Eva Maria Espinoza Gallegos', 'report_id' => '112', 'puesto' => 'Auxiliar Jr. de Compras', 'report_to' => '111', 'udn' => 'W.T.C', 'nivel' => 'Soporte Administrativo', 'correo' => 'eva.espinoza@wtcindustrial.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Eder Endiño Perez Maldonado', 'report_id' => '113', 'puesto' => 'Jefe de Operaciones ', 'report_to' => '111', 'udn' => 'W.T.C', 'nivel' => 'Coordinación', 'correo' => 'Eder.Perez@wtcindustrial.mx', 'TC' => 'X', 'PC' => ''],
            ['username' => 'David Emmanuel Morales Guerra', 'report_id' => '114', 'puesto' => 'Supervisor de Sistemas de Agua', 'report_to' => '186', 'udn' => 'W.T.C', 'nivel' => 'Soporte Administrativo', 'correo' => 'DavidMorales@wtcindustrial.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Jose Manuel Abitu Gonzalez', 'report_id' => '115', 'puesto' => 'Supervisor de Mantenimiento', 'report_to' => '186', 'udn' => 'W.T.C', 'nivel' => 'Soporte Administrativo', 'correo' => 'Joseabitu@wtcindustrial.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Jose Jair Gallegos Peralta', 'report_id' => '116', 'puesto' => 'Coordinador de Seguridad', 'report_to' => '239', 'udn' => 'EOS', 'nivel' => 'Coordinación', 'correo' => 'JairGallegos@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Jose Luis Sanchez', 'report_id' => '117', 'puesto' => 'Subgerente de Ventas y Marketing', 'report_to' => '110', 'udn' => 'W.T.C', 'nivel' => 'Coordinación', 'correo' => 'LuisSanchez@wtcindustrial.mx', 'TC' => 'X', 'PC' => ''],
            ['username' => 'Andrea Sanchez', 'report_id' => '118', 'puesto' => 'Asesor Comercial ', 'report_to' => '117', 'udn' => 'W.T.C', 'nivel' => 'Soporte Administrativo', 'correo' => 'AndreaSanchez@wtcindustrial.mx', 'TC' => 'X', 'PC' => ''],
            ['username' => 'Paulina Aldrett', 'report_id' => '119', 'puesto' => 'Asesor Comercial ', 'report_to' => '117', 'udn' => 'W.T.C', 'nivel' => 'Soporte Administrativo', 'correo' => 'PaulinaAldrett@wtcindustrial.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Blanca Gonzalez Campos', 'report_id' => '25', 'puesto' => 'Auxiliar de Capital Humano', 'report_to' => '124', 'udn' => 'META', 'nivel' => 'Soporte Administrativo', 'correo' => 'blancagonzalez@valoran.com.mx ', 'TC' => '', 'PC' => ''],
            ['username' => 'César Ramos Salazar', 'report_id' => '120', 'puesto' => 'Director de META', 'report_to' => '2', 'udn' => 'META', 'nivel' => 'Dirección', 'correo' => 'CésarRamos@valoran.com.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Eric Eduardo Gómez', 'report_id' => '121', 'puesto' => 'Analista Jr. de Capital Humano', 'report_to' => '124', 'udn' => 'META', 'nivel' => 'Soporte Administrativo', 'correo' => 'EricGomez@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Marcela Salazar Lozano', 'report_id' => '122', 'puesto' => 'Ingeniero de Soporte Sr.', 'report_to' => '41', 'udn' => 'Corporativo', 'nivel' => 'Coordinación', 'correo' => 'Marcelasalazar@valoran.com.mx ', 'TC' => 'X', 'PC' => ''],
            ['username' => 'Jose Antonio Hernandez García', 'report_id' => '123', 'puesto' => 'Ingeniero de Soporte ', 'report_to' => '122', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'AntonioHernandez@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Salma Fernanda Luna Avila', 'report_id' => '124', 'puesto' => 'Coordinador de Capital Humano', 'report_to' => '120', 'udn' => 'META', 'nivel' => 'Coordinación', 'correo' => 'SalmaLuna@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Michell Palomo Tello', 'report_id' => '125', 'puesto' => 'Coordinador de Comercialización', 'report_to' => '120', 'udn' => 'META', 'nivel' => 'Soporte Administrativo', 'correo' => 'michellpalomo@valoran.com.mx', 'TC' => 'X', 'PC' => ''],
            ['username' => 'Karla Paulina Tellez Sanchez', 'report_id' => '126', 'puesto' => 'Asistente de Dirección', 'report_to' => '120', 'udn' => 'META', 'nivel' => 'Soporte Administrativo', 'correo' => 'KarlaTellez@valoran.com.mx', 'TC' => 'X', 'PC' => ''],
            ['username' => 'Christian Alejandro Ontiveros Sandoval', 'report_id' => '127', 'puesto' => 'Coordinador de Sistemas de Gestión Integral', 'report_to' => '120', 'udn' => 'META', 'nivel' => 'Coordinación', 'correo' => 'ChristianOntiveros@valoran.com.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Melina Elizabeth Berlanga Ramirez ', 'report_id' => '128', 'puesto' => 'Coordinador de Compras', 'report_to' => '159', 'udn' => 'META', 'nivel' => 'Coordinación', 'correo' => 'MelinaBerlanga@valoran.com.mx', 'TC' => 'X', 'PC' => ''],
            ['username' => 'Rodolfo Cruz Hernandez', 'report_id' => '129', 'puesto' => 'Coordinador de Seguridad', 'report_to' => '239', 'udn' => 'EOS', 'nivel' => 'Coordinación', 'correo' => 'RodolfoCruz@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Victor Manuel Zambrano Moctezuma', 'report_id' => '131', 'puesto' => 'Auditor', 'report_to' => '220', 'udn' => 'META', 'nivel' => 'Soporte Administrativo', 'correo' => 'VictorZambrano@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Gustavo Gastelum', 'report_id' => '132', 'puesto' => 'Gerente de Contraloria', 'report_to' => '159', 'udn' => 'META', 'nivel' => 'Gerencia', 'correo' => 'GustavoGastelum@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Cesar Emmanuel Vazquez Montes De Oca', 'report_id' => '133', 'puesto' => 'Encargado de Almacen', 'report_to' => '128', 'udn' => 'META', 'nivel' => 'Soporte Administrativo', 'correo' => 'CesarVazquez@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Mayra Licet Castorena Alvarado', 'report_id' => '134', 'puesto' => 'Analista Jr de Administración', 'report_to' => '220', 'udn' => 'META', 'nivel' => 'Soporte Administrativo', 'correo' => 'MayraCastorena@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Wendy Berenice Rios Martinez', 'report_id' => '135', 'puesto' => 'Contador IFRS', 'report_to' => '132', 'udn' => 'META', 'nivel' => 'Coordinación', 'correo' => 'WendyRios@valoran.com.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Melissa Hernandez Venegas ', 'report_id' => '136', 'puesto' => 'Auxiliar Contable', 'report_to' => '135', 'udn' => 'META', 'nivel' => 'Soporte Administrativo', 'correo' => 'MelissaHernandez@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Karla Maria Saavedra Rangel', 'report_id' => '137', 'puesto' => 'Tesorera', 'report_to' => '159', 'udn' => 'META', 'nivel' => 'Soporte Administrativo', 'correo' => 'KarlaSaavedra@valoran.com.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Juan Enrique Gonzalez Azuara ', 'report_id' => '138', 'puesto' => 'Gerente de Operaciones', 'report_to' => '120', 'udn' => 'META', 'nivel' => 'Gerencia', 'correo' => 'JuanGonzalez@valoran.com.mx', 'TC' => '', 'PC' => 'X'],
            ['username' => 'Wendi Araceli Castillo Noz', 'report_id' => '139', 'puesto' => 'Analista Sr. Liquidador', 'report_to' => '138', 'udn' => 'META', 'nivel' => 'Coordinación', 'correo' => 'WendiCastillo@valoran.com.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Alma Rosa Ibarra Zavala', 'report_id' => '140', 'puesto' => 'Auxiliar de Liquidación', 'report_to' => '139', 'udn' => 'META', 'nivel' => 'Soporte Administrativo', 'correo' => 'AlmaIbarra@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Maria Mireya Moreno Rodriguez', 'report_id' => '141', 'puesto' => 'Auxiliar de Liquidación', 'report_to' => '139', 'udn' => 'META', 'nivel' => 'Soporte Administrativo', 'correo' => '', 'TC' => '', 'PC' => ''],
            ['username' => 'Vacante', 'report_id' => '142', 'puesto' => 'Gerente de Mantenimiento', 'report_to' => '120', 'udn' => 'META', 'nivel' => 'Gerencia', 'correo' => '', 'TC' => '', 'PC' => 'X'],
            ['username' => 'Lorena Moncada Haaz', 'report_id' => '159', 'puesto' => 'Gerente Administrativo ', 'report_to' => '120', 'udn' => 'META', 'nivel' => 'Gerencia', 'correo' => 'lorenamoncada@valoran.com.mx', 'TC' => '', 'PC' => 'X'],
            ['username' => 'Jesus Salvador Díaz Castillo', 'report_id' => '160', 'puesto' => 'Contador Jr.', 'report_to' => '135', 'udn' => 'META', 'nivel' => 'Soporte Administrativo', 'correo' => 'salvadordiaz@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Oscar Arnulfo Bravo Guzman', 'report_id' => '246', 'puesto' => 'Auxiliar Administrativo Contable', 'report_to' => '37', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'OscarBravo@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Brenda Berenice Alvarado Moran', 'report_id' => '161', 'puesto' => 'Coordinador de Contabilidad', 'report_to' => '39', 'udn' => 'Corporativo', 'nivel' => 'Coordinación', 'correo' => 'BrendaAlvarado@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Vacante', 'report_id' => '162', 'puesto' => 'Auxiliar Administrativo', 'report_to' => '68', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => '', 'TC' => '', 'PC' => ''],
            ['username' => 'Viviana Anaya', 'report_id' => '163', 'puesto' => 'Ingeniero de Soporte', 'report_to' => '122', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'vivianaanaya@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Eduardo Quiroz', 'report_id' => '164', 'puesto' => 'Analista Jr. de Sistemas de Información', 'report_to' => '42', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'eduardoquiroz@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Gerardo García', 'report_id' => '165', 'puesto' => 'Auxiliar Administrativo', 'report_to' => '8', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'juangarcia@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Karen Alejandra Bravo Vidales', 'report_id' => '166', 'puesto' => 'Gestora de Bienestar y Programas', 'report_to' => '49', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'karenbravo@paraserfeliz.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Verónica Zuñiga García', 'report_id' => '168', 'puesto' => 'Gerente de Desarrollo de Negocios', 'report_to' => '4', 'udn' => 'Corporativo', 'nivel' => 'Gerencia', 'correo' => 'veronicazuniga@valoran.com.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Vacante', 'report_id' => '170', 'puesto' => 'Auditor Contraloria', 'report_to' => '28', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => '', 'TC' => '', 'PC' => ''],
            ['username' => 'Belen Fabiola Ramírez Orenalas', 'report_id' => '172', 'puesto' => 'Analista de Capacitación y Desarrollo', 'report_to' => '48', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'FabiolaRamirez@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Ignacio Rico', 'report_id' => '173', 'puesto' => 'Director Comité Auditoría', 'report_to' => '178', 'udn' => 'Corporativo', 'nivel' => 'Dirección', 'correo' => 'ignaciorico@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Francisco Figueroa', 'report_id' => '174', 'puesto' => 'Gerente de Auditoría Interna', 'report_to' => '173', 'udn' => 'Corporativo', 'nivel' => 'Gerencia', 'correo' => 'franciscofigueroa@valoranext.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'David Castro', 'report_id' => '175', 'puesto' => 'Coordinador Jr. De Auditoría', 'report_to' => '174', 'udn' => 'Corporativo', 'nivel' => 'Coordinación', 'correo' => 'davidcastro@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Citlali Reyes', 'report_id' => '176', 'puesto' => 'Analista de Auditoria Sr.', 'report_to' => '175', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => 'citlalyreyes@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Vacante', 'report_id' => '177', 'puesto' => 'Auxiliar Administrativo ', 'report_to' => '175', 'udn' => 'Corporativo', 'nivel' => 'Soporte Administrativo', 'correo' => '', 'TC' => '', 'PC' => ''],
            ['username' => 'Cecilia Rangel ', 'report_id' => '178', 'puesto' => 'Presidencia', 'report_to' => null, 'udn' => 'Vexa Capital', 'nivel' => 'N/A', 'correo' => 'ceciliarangel@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Ruben Castillo ', 'report_id' => '179', 'puesto' => 'Gerente de Planación Financiera y Estratégica', 'report_to' => '178', 'udn' => 'Vexa Capital', 'nivel' => 'Gerencia', 'correo' => 'RubenCastillo@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Citlalic Valadez', 'report_id' => '180', 'puesto' => 'Auxiliar Administrativo', 'report_to' => '179', 'udn' => 'Vexa Capital', 'nivel' => 'Soporte Administrativo', 'correo' => 'CitlalicValadez@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Carmen Rubio', 'report_id' => '181', 'puesto' => 'Coordinador Administrativo', 'report_to' => '179', 'udn' => 'Vexa Capital', 'nivel' => 'Coordinación', 'correo' => 'carmenrubio@valoran.com.mx', 'TC' => '', 'PC' => 'X'],
            ['username' => 'Evelia Tavares Zavala', 'report_id' => '182', 'puesto' => 'Contador Sr.', 'report_to' => '181', 'udn' => 'Vexa Capital', 'nivel' => 'Soporte Administrativo', 'correo' => 'EveliaTavares@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Lorena Infante', 'report_id' => '183', 'puesto' => 'Auxiliar Administrativo', 'report_to' => '181', 'udn' => 'Vexa Capital', 'nivel' => 'Soporte Administrativo', 'correo' => '', 'TC' => '', 'PC' => ''],
            ['username' => 'Diana Almendarez', 'report_id' => '184', 'puesto' => 'Contador Jr.', 'report_to' => '182', 'udn' => 'Vexa Capital', 'nivel' => 'Soporte Administrativo', 'correo' => 'dalmendarez@vexacapital.com', 'TC' => '', 'PC' => ''],
            ['username' => 'Gabriela Medina', 'report_id' => '185', 'puesto' => 'Contador Jr.', 'report_to' => '182', 'udn' => 'Vexa Capital', 'nivel' => 'Soporte Administrativo', 'correo' => '', 'TC' => '', 'PC' => ''],
            ['username' => 'Vacante', 'report_id' => '186', 'puesto' => 'Superintendente de Mantenimiento', 'report_to' => '111', 'udn' => 'W.T.C', 'nivel' => 'Coordinación', 'correo' => '', 'TC' => '', 'PC' => ''],
            ['username' => 'Alberto Rangel Mancilla', 'report_id' => '187', 'puesto' => 'Presidencia', 'report_to' => null, 'udn' => 'Fundación Nutriendo', 'nivel' => 'N/A', 'correo' => 'arangel@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Veronica Guzmán', 'report_id' => '188', 'puesto' => 'Dirección Ejecutiva', 'report_to' => '187', 'udn' => 'Fundación Nutriendo', 'nivel' => 'Dirección', 'correo' => 'veronicaguzman@nutriendo.org', 'TC' => '', 'PC' => ''],
            ['username' => 'Olivia Bours', 'report_id' => '189', 'puesto' => 'Coordinador de Programa de Recaudación e Imagen', 'report_to' => '188', 'udn' => 'Fundación Nutriendo', 'nivel' => 'Coordinación', 'correo' => 'oliviabgarcia@nutriendo.org', 'TC' => 'X', 'PC' => ''],
            ['username' => 'Rodolfo Gonzalez ', 'report_id' => '190', 'puesto' => 'Recaudación Fondos', 'report_to' => '189', 'udn' => 'Fundación Nutriendo', 'nivel' => 'Soporte Administrativo', 'correo' => 'rodolfogonzalez@nutriendo.org', 'TC' => '', 'PC' => ''],
            ['username' => 'Ricardo Almeria', 'report_id' => '191', 'puesto' => 'Recaudación Fondos', 'report_to' => '189', 'udn' => 'Fundación Nutriendo', 'nivel' => 'Soporte Administrativo', 'correo' => 'RicardoArmeria@nutriendo.org', 'TC' => '', 'PC' => ''],
            ['username' => 'Andrea Silva', 'report_id' => '192', 'puesto' => 'Relaciones publicas y voluntariado ', 'report_to' => '189', 'udn' => 'Fundación Nutriendo', 'nivel' => 'Soporte Administrativo', 'correo' => 'AndreaSilva@nutriendo.org', 'TC' => '', 'PC' => ''],
            ['username' => 'Samantha Jimenez', 'report_id' => '193', 'puesto' => 'Atención a Padrinos, Comunicación y Voluntariado', 'report_to' => '192', 'udn' => 'Fundación Nutriendo', 'nivel' => 'Soporte Administrativo', 'correo' => 'Padrinos@nutriendo.org', 'TC' => '', 'PC' => ''],
            ['username' => 'Yolanda Castillo', 'report_id' => '194', 'puesto' => 'Administración', 'report_to' => '188', 'udn' => 'Fundación Nutriendo', 'nivel' => 'Coordinación', 'correo' => 'Contacto@nutriendo.org', 'TC' => '', 'PC' => 'X'],
            ['username' => 'Yolanda Gaytan ', 'report_id' => '195', 'puesto' => 'Coordinador de Programa Social', 'report_to' => '188', 'udn' => 'Fundación Nutriendo', 'nivel' => 'Coordinación', 'correo' => 'yolandagaytan@nutriendo.org', 'TC' => 'X', 'PC' => ''],
            ['username' => 'Hiram Gallegos', 'report_id' => '196', 'puesto' => 'Auxiliar Logistica', 'report_to' => '195', 'udn' => 'Fundación Nutriendo', 'nivel' => 'Soporte Administrativo', 'correo' => '', 'TC' => '', 'PC' => 'X'],
            ['username' => 'Reynaldo Gaytan', 'report_id' => '197', 'puesto' => 'Auxiliar Logistica', 'report_to' => '195', 'udn' => 'Fundación Nutriendo', 'nivel' => 'Soporte Administrativo', 'correo' => '', 'TC' => '', 'PC' => 'X'],
            ['username' => 'Miriam De La Rosa', 'report_id' => '198', 'puesto' => 'Asesor de Programa Social', 'report_to' => '195', 'udn' => 'Fundación Nutriendo', 'nivel' => 'Soporte Administrativo', 'correo' => '', 'TC' => '', 'PC' => ''],
            ['username' => 'Claudia Oliva', 'report_id' => '199', 'puesto' => 'Asesor de Programa Social', 'report_to' => '195', 'udn' => 'Fundación Nutriendo', 'nivel' => 'Soporte Administrativo', 'correo' => 'ClaudiaRodriguez@nutriendo.org', 'TC' => '', 'PC' => ''],
            ['username' => 'Marco Ruiz', 'report_id' => '200', 'puesto' => 'Gestor Proyectos Especiales', 'report_to' => '188', 'udn' => 'Fundación Nutriendo', 'nivel' => 'Soporte Administrativo', 'correo' => 'MarcoRuiz@ranman.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Gerardo Diaz Reigadas', 'report_id' => '201', 'puesto' => 'Director de Construcción', 'report_to' => '2', 'udn' => 'Construcción', 'nivel' => 'Dirección', 'correo' => 'GerardoDiaz@valoran.com.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Ulises Mexicano ', 'report_id' => '202', 'puesto' => 'Gerencia de Obra', 'report_to' => '201', 'udn' => 'Construcción', 'nivel' => 'Gerencia', 'correo' => 'ulisesmexicano@valoran.com.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Juan Mateo Beltrán González', 'report_id' => '203', 'puesto' => 'Juridico ', 'report_to' => '202', 'udn' => 'Construcción', 'nivel' => 'Especialista', 'correo' => 'JuanBeltran@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'José Francisco Olmos Guerrero', 'report_id' => '204', 'puesto' => 'Coordinación Tecnica', 'report_to' => '201', 'udn' => 'Construcción', 'nivel' => 'Coordinación', 'correo' => 'joseolmos@valoran.com.mx', 'TC' => 'X', 'PC' => ''],
            ['username' => 'Luis Aristeo Mendez Muñoz', 'report_id' => '205', 'puesto' => 'Coordinación Técnica', 'report_to' => '202', 'udn' => 'Construcción', 'nivel' => 'Coordinación', 'correo' => 'luis.mendez@valoran.com.mx', 'TC' => 'X', 'PC' => ''],
            ['username' => 'Esteban Martinez', 'report_id' => '206', 'puesto' => 'Auxiliar Técnico ', 'report_to' => '205', 'udn' => 'Construcción', 'nivel' => 'Soporte Administrativo', 'correo' => 'EstebanMartínez@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Roque Godínez', 'report_id' => '207', 'puesto' => 'Topografía', 'report_to' => '205', 'udn' => 'Construcción', 'nivel' => 'Soporte Administrativo', 'correo' => '', 'TC' => '', 'PC' => ''],
            ['username' => 'Clemente Santiago Martinez', 'report_id' => '208', 'puesto' => 'Topografía', 'report_to' => '205', 'udn' => 'Construcción', 'nivel' => 'Soporte Administrativo', 'correo' => '', 'TC' => '', 'PC' => ''],
            ['username' => 'Javier Flores Santana', 'report_id' => '209', 'puesto' => 'Residente de Obra', 'report_to' => '202', 'udn' => 'Construcción', 'nivel' => 'Soporte Administrativo', 'correo' => 'JavierFlores@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Jose Alfredo Castillo Lopez', 'report_id' => '210', 'puesto' => 'Residente de Obra', 'report_to' => '202', 'udn' => 'Construcción', 'nivel' => 'Soporte Administrativo', 'correo' => 'AlfredoCastillo@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Jose Orlando Sánchez Salazar', 'report_id' => '211', 'puesto' => 'Residente de Obra', 'report_to' => '202', 'udn' => 'Construcción', 'nivel' => 'Soporte Administrativo', 'correo' => 'orlandosanchez@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Gabriel Urrutia Rodríguez', 'report_id' => '212', 'puesto' => 'Coordinación de Costos, Estimaciones y Programación ', 'report_to' => '202', 'udn' => 'Construcción', 'nivel' => 'Coordinación', 'correo' => 'gabriel.urrutia@valoran.com.mx', 'TC' => 'X', 'PC' => ''],
            ['username' => 'Vacante', 'report_id' => '213', 'puesto' => 'Ayudante Estimaciones-Costos', 'report_to' => '212', 'udn' => 'Construcción', 'nivel' => 'Soporte Administrativo', 'correo' => '', 'TC' => '', 'PC' => ''],
            ['username' => 'Vacante', 'report_id' => '214', 'puesto' => 'Responsable Programación ', 'report_to' => '212', 'udn' => 'Construcción', 'nivel' => 'Soporte Administrativo', 'correo' => '', 'TC' => '', 'PC' => ''],
            ['username' => 'Vacante', 'report_id' => '215', 'puesto' => 'Coordinador Administrativa', 'report_to' => '201', 'udn' => 'Construcción', 'nivel' => 'Coordinación', 'correo' => '', 'TC' => '', 'PC' => ''],
            ['username' => 'David Espiosa Espinosa', 'report_id' => '216', 'puesto' => 'Gestor de Cobranza', 'report_to' => '83', 'udn' => 'Valle de los cedros', 'nivel' => 'Soporte Administrativo', 'correo' => '', 'TC' => '', 'PC' => ''],
            ['username' => 'Gustavo Alberto Perez Guerrero', 'report_id' => '217', 'puesto' => 'Gestor de Cobranza', 'report_to' => '83', 'udn' => 'Valle de los cedros', 'nivel' => 'Soporte Administrativo', 'correo' => '', 'TC' => '', 'PC' => ''],
            ['username' => 'Julio Enrique Rodriguez Martinez', 'report_id' => '218', 'puesto' => 'Gestor de Cobranza', 'report_to' => '83', 'udn' => 'Valle de los cedros', 'nivel' => 'Soporte Administrativo', 'correo' => '', 'TC' => '', 'PC' => ''],
            ['username' => 'Jessica Monserrat Fernandez Vazquez ', 'report_id' => '219', 'puesto' => 'Coordinador de Proyectos Estratégicos y Análisis Financiero', 'report_to' => '120', 'udn' => 'META', 'nivel' => 'Coordinación', 'correo' => 'jessicafernandez@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Andrea Magaña Saucedo', 'report_id' => '220', 'puesto' => 'Coordinador Sr. De Administración', 'report_to' => '159', 'udn' => 'META', 'nivel' => 'Coordinación', 'correo' => 'andreamagana@valoran.com.mx', 'TC' => '', 'PC' => 'X'],
            ['username' => 'Gabriela Ramirez Castillo', 'report_id' => '221', 'puesto' => 'Auxiliar de compras', 'report_to' => '128', 'udn' => 'META', 'nivel' => 'soporte Administrativo', 'correo' => 'gabrielaramires@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Juan Carlos López Natarén', 'report_id' => '222', 'puesto' => 'Auxiliar Contable', 'report_to' => '220', 'udn' => 'META', 'nivel' => 'Soporte Administrativo', 'correo' => 'juancarloslopez@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Vacante', 'report_id' => '223', 'puesto' => 'Contador Sr ', 'report_to' => '220', 'udn' => 'META', 'nivel' => 'Soporte Administrativo', 'correo' => '', 'TC' => '', 'PC' => ''],
            ['username' => 'Vacante', 'report_id' => '224', 'puesto' => 'Auxiliar de Tesoreria ', 'report_to' => '137', 'udn' => 'META', 'nivel' => 'Soporte Administrativo', 'correo' => '', 'TC' => '', 'PC' => ''],
            ['username' => 'Gustavo Correa Avalos ', 'report_id' => '225', 'puesto' => 'Coordinador de Mantenimiento ', 'report_to' => '120', 'udn' => 'META', 'nivel' => 'Gerencia', 'correo' => 'gustavocorrea@valoran.com.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Teresita Rodriguez Alvarado', 'report_id' => '226', 'puesto' => 'JEFE DE OPERACIONES NORTE', 'report_to' => '138', 'udn' => 'META', 'nivel' => 'Coordinación', 'correo' => 'jefatura.norte@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Luis Enrique Gutierrez Alvarez', 'report_id' => '227', 'puesto' => 'JEFE DE OPERACIONES NORTE', 'report_to' => '138', 'udn' => 'META', 'nivel' => 'Coordinación', 'correo' => 'jefatura.norte@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Juan Manuel Ramirez Bueno', 'report_id' => '228', 'puesto' => 'JEFE DE OPERACIONES NORTE', 'report_to' => '138', 'udn' => 'META', 'nivel' => 'Coordinación', 'correo' => 'jefatura.oriente@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Hugo Martinez Reyna', 'report_id' => '229', 'puesto' => 'JEFE DE OPERACIONES NORTE', 'report_to' => '138', 'udn' => 'META', 'nivel' => 'Coordinación', 'correo' => 'jefatura.poniente@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Agustin Aguilar Hernandez', 'report_id' => '230', 'puesto' => 'JEFE DE OPERACIONES PONIENTE', 'report_to' => '138', 'udn' => 'META', 'nivel' => 'Coordinación', 'correo' => 'jefatura.norte@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Alma Carmona', 'report_id' => '231', 'puesto' => 'JEFE DE OPERACIÓNES  PONIENTE ', 'report_to' => '138', 'udn' => 'META', 'nivel' => 'Coordinación', 'correo' => 'jefatura.poniente@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Omar Zavala Diaz', 'report_id' => '232', 'puesto' => 'JEFE DE OPERACIONES PONIENTE', 'report_to' => '138', 'udn' => 'META', 'nivel' => 'Coordinación', 'correo' => 'jefatura.norte@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Nora Elidia Aguilar Martinez', 'report_id' => '233', 'puesto' => 'JEFE DE OPERACIONES PONIENTE', 'report_to' => '138', 'udn' => 'META', 'nivel' => 'Coordinación', 'correo' => 'jefatura.poniente@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Cristyan David Hernandez Perez', 'report_id' => '234', 'puesto' => 'JEFE DE OPERACIONES ORIENTE', 'report_to' => '138', 'udn' => 'META', 'nivel' => 'Coordinación', 'correo' => 'jefatura.poniente@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Jose Antonio Cabrera Chavez', 'report_id' => '235', 'puesto' => 'JEFE DE OPERACIONES ORIENTE', 'report_to' => '138', 'udn' => 'META', 'nivel' => 'Coordinación', 'correo' => 'jefatura.oriente@valoran.com.mx', 'TC' => 'X', 'PC' => ''],
            ['username' => 'Oscar Hernandez Camarillo', 'report_id' => '236', 'puesto' => 'JEFE DE OPERACIONES ORIENTE', 'report_to' => '138', 'udn' => 'META', 'nivel' => 'Coordinación', 'correo' => 'jefatura.oriente@valoran.com.mx', 'TC' => 'X', 'PC' => ''],
            ['username' => 'Vacante', 'report_id' => '237', 'puesto' => 'JEFE DE OPERACIONES ORIENTE', 'report_to' => '138', 'udn' => 'META', 'nivel' => 'Coordinación', 'correo' => 'jefatura.oriente@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Guillermo Romero Ortega', 'report_id' => '238', 'puesto' => 'JEFE DE OPERACIÓN Y AUXILIO VIAL ', 'report_to' => '138', 'udn' => 'META', 'nivel' => 'Coordinación', 'correo' => 'jefatura.oriente@valoran.com.mx', 'TC' => 'X', 'PC' => ''],
            ['username' => 'Rogelio Lozano De Leon', 'report_id' => '167', 'puesto' => 'Director de Seguridad Corporativa y Prevención de Riesgos', 'report_to' => '2', 'udn' => 'EOS', 'nivel' => 'Dirección', 'correo' => 'RogelioLozano@valoran.com.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Miguel Angel Merlos ', 'report_id' => '239', 'puesto' => 'Gerente de operaciones de seguridad', 'report_to' => '167', 'udn' => 'EOS', 'nivel' => 'Gerencia', 'correo' => 'Miguelmerlos@valoran.com.mx', 'TC' => 'X', 'PC' => 'X'],
            ['username' => 'Natalia Vazquez', 'report_id' => '240', 'puesto' => 'Coordinadora de Servicios Corporativos de Seguridad', 'report_to' => '167', 'udn' => 'EOS', 'nivel' => 'Coordinación', 'correo' => 'nataliavazquez@valoran.com.mx', 'TC' => 'X', 'PC' => ''],
            ['username' => 'Jose Santiago Gil ', 'report_id' => '241', 'puesto' => 'Coordinador de Protección Civil ', 'report_to' => '239', 'udn' => 'EOS', 'nivel' => 'Soporte Administrativo', 'correo' => 'JoseGil@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Guadalupe Celina Del Valle Cortes', 'report_id' => '242', 'puesto' => 'Coordinador de Inteligencia', 'report_to' => '167', 'udn' => 'EOS', 'nivel' => 'Coordinación', 'correo' => 'celinadelvalle@valoran.com.mx', 'TC' => 'X', 'PC' => ''],
            ['username' => 'Ricardo Reyes Robledo', 'report_id' => '243', 'puesto' => 'Coordinador de Seguridad', 'report_to' => '167', 'udn' => 'EOS', 'nivel' => 'Coordinación', 'correo' => 'ricardoreyes@valoran.com.mx', 'TC' => 'X', 'PC' => ''],
            ['username' => 'Américo Israel Sánchez Vázquez', 'report_id' => '244', 'puesto' => 'Coordinador Administrativo', 'report_to' => '167', 'udn' => 'EOS', 'nivel' => 'Coordinación', 'correo' => 'AmericoSanchez@valoran.com.mx', 'TC' => '', 'PC' => ''],
            ['username' => 'Jesús Adolfo Jacquez Rodríguez', 'report_id' => '245', 'puesto' => 'Supervisor de Monitores', 'report_to' => '167', 'udn' => 'EOS', 'nivel' => 'Coordinación', 'correo' => 'JesusJacquez@valoran.com.mx', 'TC' => '', 'PC' => ''],
        ];

        foreach ($data as $d) {
            
            $job = Job::firstOrCreate([
                'name' => $d['puesto']                
            ]);
            $level = Level::firstOrCreate([
                'name' => $d['nivel']
            ]);
            $udn = Udn::firstOrCreate([
                'name' => $d['udn']
            ]);            
            $user = User::create([
                'name' => $d["username"],
                'email' => $d['correo'] ?? (str_replace(" ", "", $d["username"]) . "@valoran.com.mx"),
                'job_id' => $job->id,
                'report_to' => $d['report_to'],
                'level_id' => $level->id,
                'udn_id' => $udn->id,                
                'report_id' => $d['report_id'],          
                'puesto_critico' => $d['PC'] == 'X',
                'talento_clave' => $d['TC'] == 'X'                  
            ]);


        }
    }
}
