<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Experience;
use App\Models\Job;
use App\Models\JobCompetence;
use App\Models\Knowledge;


class VDCPuestosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $job = Job::firstOrCreate(['name' => 'Director de Valle de los Cedros']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Gestión de Recursos', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Director de Valle de los Cedros']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Financieros', 'notas' => 'Matemáticas Financieras\n- Evaluación de Proyectos Financieros\n- Entendimiento de Estados Financieros\n- Inversiones\n- Presupuestos']);
        $job = Job::firstOrCreate(['name' => 'Director de Valle de los Cedros']);
        Experience::create(['job_id' => $job->id, 'name' => 'Co-Diseñar Estrategias Comerciales con la Gerencia Comercial', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Gestión del Riesgo', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Normativas Contables ', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Orientación al Cliente/Servicio', 'notas' => 'Mucha empatía']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Normativas Fiscales ', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Normativas y Sistemas de Gestión de Calidad', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Legal (bases)', 'notas' => "Contractual\n- Entendimiento de los temas legales Para identificar si puede existir algún problema, siempre apoyándose DEL abogado Para prevenirlos y solucionarloS"]);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Conocimientos Comerciales', 'notas' => "Estrategias Comerciales\n- Construcción de Equipos de Ventas"]);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Mantenimiento y construcción de fosas (bases)', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Excel (avanzado)', 'notas' => 'gracias a ellos he podido ir generando los controles y reportes que se requieren para administración adecuada de la unidad de negocio. Una vez que se terminen de desarrollar los sistemas necesarios, el manejo de Excel avanzado tal vez ya no sea tan importante. Esto puede llevar entre uno y dos años.']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Administración de Proyectos', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Marco Legal Laboral (bases)', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Coordinador de Servicio al Cliente']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Sentido común', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Coordinador de Servicio al Cliente']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Office', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Construcción de relaciones', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Procesamiento de datos ', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Orientación al cliente', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Atención al cliente ', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Mejoramiento continuo ', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Redes sociales', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Retroalimentación y control ', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Escucha activa', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Gestión del conflicto', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Auxiliar de Diseño']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Creatividad', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Auxiliar de Diseño']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Adobe Photoshop', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Destreza comunicativa', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Adobe Illustrador', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Trabajo en equipo', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Adobe Premier', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Forjador de cultura', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Paquetería Office', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Innovación', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Mercadotecnia', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Orientación al servicio', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'CopyWriting', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Fotografía y video', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Gerente Administrativo']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Visión Financiera y del Negocio', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Gerente Administrativo']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Sistemas Administrativos Contables (ERP)', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Gestión del Riesgo', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Normativas Contables', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Gestión de la Información', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Normativas Fiscales', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Gestión de Recursos', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Elaboración e Interpretación de Estados Financieros ', 'notas' => "Estados financieros/contables básicos:\n- Estado de Resultados\n- Balance General\n- Flujo de Efectivo\n- Estado de Cambios de Capital"]);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Sentido de Urgencia', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Elaboración, Manejo y Control de Presupuestos', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Dominio y Cumplimiento Normativo', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Administración de Nóminas (IMSS, INFONAVIT, FONACOT...)', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Anticipación de Problemas', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Manejo de Bancos, Créditos Bancarios.. ', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Toma de Decisiones Asertiva', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Marco Legal (bases)', 'notas' => "Corporativo\n- Laboral Para que la empresa pueda operar sin problema."]);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Marco Legal Laboral (bases)', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Excel Intermedio', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Contador General']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Atención al detalle ', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Contador General']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Paquetería Office ', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Capacidad numérica ', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Sistema Valle', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Orientación a la calidad', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Fortia', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Responsabilidad ', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Actualizaciones fiscales ', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Tolerancia a la presión', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Capacidad de análisis', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Auxiliar Administrativo']);
        $job = Job::firstOrCreate(['name' => 'Auxiliar Administrativo']);
        $job = Job::firstOrCreate(['name' => 'Encargado de Archivo']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Atención al detalle', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Encargado de Archivo']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Paquetería Office ', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Discreción', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Archivología', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Colaboración', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Cumplimiento de normas', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Confiabilidad', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Organización', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Auxiliar de Archivo']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Atención al detalle ', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Auxiliar de Archivo']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Principios básicos de organización documental', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Capacidad organizativa ', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Normativa archivística ', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Gestión de la información ', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Conservación documental', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Iniciativa', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Paquetería Microsoft Office', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Proactividad ', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Responsabilidad ', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Analista Jr. de Compras']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Capacidad de negociación', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Analista Jr. de Compras']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Paquetería Office ', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Construcción de relaciones', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Compras', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Credibilidad ', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Negociación', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Firmeza', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Relaciones con proveedores', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Planificación y organización', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Logística ', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Gestión de la trazabilidad', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Auxiliar Contable']);
        $job = Job::firstOrCreate(['name' => 'Auxiliar Contable']);
        $job = Job::firstOrCreate(['name' => 'Coordinador de Cobranza']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Negociación', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Coordinador de Cobranza']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Sistemas Administrativos Contables (ERP)', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Colaboración con áreas estratégicas/Trabajo en Equipo', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Gestión de Cobranza', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Habilidad Numérica', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Manejo de Efectivo', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Gestión de la Información', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Conciliaciones Bancarias', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Orientación al Cliente/Servicio', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Plataformas Bancarias', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Administración de Proyectos           ', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Marco Legal Laboral (bases)', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Excel Intermedio', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Coordinador de Cuentas por Cobrar']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Capacidad de asesorar ', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Coordinador de Cuentas por Cobrar']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Paquetería Office ', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Conocimiento organizativo ', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Cobranza', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Destreza comunicativa', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Manejo de efectivo', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Persistencia ', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Sistema Valle', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Persuasión ', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Contratos y servicios de la UDN ', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Capacidad de negociación ', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Auxiliar de Cobranza']);
        $job = Job::firstOrCreate(['name' => 'Auxiliar de Cobranza']);
        $job = Job::firstOrCreate(['name' => 'Gestor de Cobranza de Domiciliaria']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Orientación al servicio', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Gestor de Cobranza de Domiciliaria']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Cobranza efectiva ', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Atención al detalle', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Manejo de motocicleta', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Colaboración ', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Noción de ubicación en la ciudad', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Cumplimiento de normas', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Recuperación de cuentas vencidas', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Confiabilidad', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Organización', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Gerente de Operaciones']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Capacidad de Respuesta y Resolución', 'notas' => 'Disponibilidad.- Dar respuesta en tiempo y forma.']);
        $job = Job::firstOrCreate(['name' => 'Gerente de Operaciones']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Elaboración, Manejo y Control de Presupuestos', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Mejoramiento Continuo / Orientación a la Calidad', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Normativas y Sistemas de Gestión de Calidad', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Orientación al Cliente/Servicio ', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Normatividad COFEPRIS', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Construcción de Relaciones ', 'notas' => 'Dependencias de gobierno, clientes, proveedores']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Normatividad SEGAM', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Gestión de Recursos', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Ley de Aguas Nacionales', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Dominio y Cumplimiento Normativo', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Mantenimiento de áreas verdes', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Toma de Decisiones Asertiva', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Planta de Tratamiento de Agua Residual', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Construcción', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Softwares de Diseño', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Seguridad Patrimonial', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Administración de Proyectos           ', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Marco Legal Laboral (bases)', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Coordinador de Operaciones']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Planificación y organización', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Coordinador de Operaciones']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Normas ISO', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Orientación a los resultados', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Normativas de salubridad', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Atención al detalle', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Legislación ambiental', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Delegación y empoderamiento', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Normativas de protección civil', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Manejo de personal', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Coordinador de Operaciones y Atención al Cliente']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Orientación al Cliente/Servicio ', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Coordinador de Operaciones y Atención al Cliente']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Softwares de contabilidad (ERP)', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Gestión de Recursos', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Elaboración, Manejo y Control de Presupuestos', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Habilidad Numérica', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Estrategias de Atención al Cliente', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Sentido de Oportunidad', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Compras y manejo de almacén', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Confiabilidad', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Marco Legal Laboral (bases)', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Mejoramiento Continuo', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Capacidad de Respuesta y Disponibilidad', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Auxiliar de Operaciones']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Orientación al servicio ', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Auxiliar de Operaciones']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Paquetería Office', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Atención al detalle', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Discreción', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Cumplimiento de normas', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Planificación y organización', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Tolerancia a la presión', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Gerente Comercial']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Orientación al Mercado', 'notas' => 'Conocer bien el mercado, todo orientado hacia el y cómo llegar a él.']);
        $job = Job::firstOrCreate(['name' => 'Gerente Comercial']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Elaboración, Manejo y Control de Presupuestos', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Innovación /Creatividad', 'notas' => 'Nuevas ideas para sacar estrategias comerciales']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Planes Estratégicos Comerciales', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Comunicación Efectiva', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Mercadotecnia y Diseño', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Construcción de Relaciones', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Manejo de Medios de Comunicación', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Orientación al Cliente', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Relaciones Públicas', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Toma de Decisiones Asertiva', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Eventos Empresariales', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Administración de Proyectos', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Marco Legal Laboral (bases)', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Auxiliar de Comercialización']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Construcción de relaciones ', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Auxiliar de Comercialización']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Paquetería Office ', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Ejecutividad ', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Smartsheet', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Gestión de la trazabilidad', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Neodata', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Actualizaciones en temas facturación ', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Sistema Valle', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Mercadotécnica ', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Coordinador Comercial']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Capacidad de planificación y organización', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Coordinador Comercial']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Dominio de ventas ', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Orientación a los resultados', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Mercadotecnia', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Capacidad de asesorar ', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Técnicas de venta', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Compromiso con la organización', 'notas' => '']);
        Knowledge::create(['job_id' => $job->id, 'name' => 'Administración de presupuestos', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Capacidad de negociación', 'notas' => '']);
        JobCompetence::create(['job_id' => $job->id, 'name' => 'Desarrollo de personas ', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Director de Valle de los Cedros']);
        Experience::create(['job_id' => $job->id, 'name' => 'Co-Diseñar Estrategias Comerciales con la Gerencia Comercial', 'notas' => '']);
        Experience::create(['job_id' => $job->id, 'name' => 'Asistir a reuniones de Consejo de Administración', 'notas' => "Resultados de la UN.\n- Presupuestos"]);
        $job = Job::firstOrCreate(['name' => 'Coordinador de Servicio al Cliente']);
        $job = Job::firstOrCreate(['name' => 'Auxiliar de Diseño']);
        $job = Job::firstOrCreate(['name' => 'Gerente Administrativo']);
        Experience::create(['job_id' => $job->id, 'name' => 'Tener los reportes en tiempo y forma continuamente.', 'notas' => '']);
        Experience::create(['job_id' => $job->id, 'name' => 'Resolución favorable de auditorías internas y externas.', 'notas' => '']);
        Experience::create(['job_id' => $job->id, 'name' => 'Aumento en el % de utilidad del negocio.', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Contador General']);
        $job = Job::firstOrCreate(['name' => 'Auxiliar Administrativo']);
        $job = Job::firstOrCreate(['name' => 'Encargado de Archivo']);
        $job = Job::firstOrCreate(['name' => 'Auxiliar de Archivo']);
        $job = Job::firstOrCreate(['name' => 'Analista Jr. de Compras']);
        $job = Job::firstOrCreate(['name' => 'Auxiliar Contable']);
        $job = Job::firstOrCreate(['name' => 'Coordinador de Cobranza']);
        $job = Job::firstOrCreate(['name' => 'Coordinador de Cuentas por Cobrar']);
        $job = Job::firstOrCreate(['name' => 'Auxiliar de Cobranza']);
        $job = Job::firstOrCreate(['name' => 'Gestor de Cobranza de Domiciliaria']);
        $job = Job::firstOrCreate(['name' => 'Gerente de Operaciones']);
        Experience::create(['job_id' => $job->id, 'name' => 'Liderar procesos de atención con clientes difíciles.', 'notas' => 'Involucra el manejo de emociones (inteligencia emocional)']);
        Experience::create(['job_id' => $job->id, 'name' => 'Negociaciones exitosas con dependencias gubernamentales.', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Coordinador de Operaciones']);
        $job = Job::firstOrCreate(['name' => 'Coordinador de Operaciones y Atención al Cliente']);
        $job = Job::firstOrCreate(['name' => 'Auxiliar de Operaciones']);
        $job = Job::firstOrCreate(['name' => 'Gerente Comercial']);
        Experience::create(['job_id' => $job->id, 'name' => 'Liderar equipos de ventas.', 'notas' => '']);
        Experience::create(['job_id' => $job->id, 'name' => 'Cerrar ventas.', 'notas' => '']);
        Experience::create(['job_id' => $job->id, 'name' => 'Desarrollar agentes de ventas.', 'notas' => '']);
        $job = Job::firstOrCreate(['name' => 'Auxiliar de Comercialización']);
        $job = Job::firstOrCreate(['name' => 'Coordinador Comercial']);
    }
}
